# **CS 584-A: Natural Language Processing**
# **Homework 3**

**Name: Ankit Dhandharia**

**CWID: 20033031**

## **Goals**
The goal of HW3 is for you to get hands-on experience of utilizing Seq2Seq model for machine
translation task. You will get a deeper understanding of how the input sequence is translated to
the output sequence with the Seq2Seq model. The skills of you learnt in this homework will
benefit your understanding of a wide range of NLP tasks beyond machine translation. Please feel
free to use any packages or libraries in your implementation.


## **Task: Machine Translation**

#**1. Data preparation**

In [31]:
!pip install datasets
!pip install transformers
!pip install torchtext
!pip install torch
!pip install tensorflow
!pip install sentencepiece
!pip install sacremoses
!pip install sacrebleu
!pip install ctranslate2

Requirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (3.1.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets) (3.16.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (17.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.10/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.10/dist-packages (from datasets) (4.66.6)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.9.0,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets) (2024.9.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.10.10)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.26.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (2.4.3)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.17.1)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.23.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2024.8.30)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from yarl<2.0,>=1.12.0->aiohttp->datasets) (0.2.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.46.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.26.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2024.9.11)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.5)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.20.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.6)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (2024.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2024.8.30)
Collecting torchtext
  Downloading torchtext-0.18.0-cp310-cp310-manylinux1_x86_64.whl.metadata (7.9 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from torchtext) (4.66.6)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from torchtext) (2.32.3)
Requirement already satisfied: torch>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from torchtext) (2.5.1+cu121)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from torchtext) (1.26.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->torchtext) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->torchtext) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->torchtext) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->torchtext) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->torchtext) (2024.9.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->torchtext) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch>=2.3.0->torchtext) (1.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->torchtext) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->torchtext) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->torchtext) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->torchtext) (2024.8.30)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=2.3.0->torchtext) (3.0.2)
Downloading torchtext-0.18.0-cp310-cp310-manylinux1_x86_64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 29.4 MB/s eta 0:00:00
Installing collected packages: torchtext
Successfully installed torchtext-0.18.0
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.5.1+cu121)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch) (2024.9.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: tensorflow in /usr/local/lib/python3.10/dist-packages (2.17.1)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: h5py>=3.10.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.12.1)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.4.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (4.25.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow) (75.1.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.5.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.16.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.67.1)
Requirement already satisfied: tensorboard<2.18,>=2.17 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.17.1)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.5.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.37.1)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.26.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.0)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->tensorflow) (0.0.8)
Requirement already satisfied: optree in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->tensorflow) (0.13.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow) (2024.8.30)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.18,>=2.17->tensorflow) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.18,>=2.17->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.18,>=2.17->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.18,>=2.17->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras>=3.2.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras>=3.2.0->tensorflow) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->tensorflow) (0.1.2)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (0.2.0)
Collecting sacremoses
  Downloading sacremoses-0.1.1-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.10/dist-packages (from sacremoses) (2024.9.11)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from sacremoses) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from sacremoses) (1.4.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sacremoses) (4.66.6)
Downloading sacremoses-0.1.1-py3-none-any.whl (897 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.5/897.5 kB 17.1 MB/s eta 0:00:00
Installing collected packages: sacremoses
Successfully installed sacremoses-0.1.1
Collecting sacrebleu
  Downloading sacrebleu-2.4.3-py3-none-any.whl.metadata (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.8/51.8 kB 3.5 MB/s eta 0:00:00
Collecting portalocker (from sacrebleu)
  Downloading portalocker-2.10.1-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.10/dist-packages (from sacrebleu) (2024.9.11)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.10/dist-packages (from sacrebleu) (0.9.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from sacrebleu) (1.26.4)
Collecting colorama (from sacrebleu)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from sacrebleu) (5.3.0)
Downloading sacrebleu-2.4.3-py3-none-any.whl (103 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.0/104.0 kB 8.5 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading portalocker-2.10.1-py3-none-any.whl (18 kB)
Installing collected packages: portalocker, colorama, sacrebleu
Successfully installed colorama-0.4.6 portalocker-2.10.1 sacrebleu-2.4.3
Collecting ctranslate2
  Downloading ctranslate2-4.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from ctranslate2) (75.1.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from ctranslate2) (1.26.4)
Requirement already satisfied: pyyaml<7,>=5.3 in /usr/local/lib/python3.10/dist-packages (from ctranslate2) (6.0.2)
Downloading ctranslate2-4.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.4/38.4 MB 12.6 MB/s eta 0:00:00
Installing collected packages: ctranslate2
Successfully installed ctranslate2-4.5.0

In [4]:
from datasets import load_dataset
dataset = load_dataset("Muennighoff/flores200", "all")

Downloading data:   0%|          | 0.00/25.6M [00:00<?, ?B/s]

Generating dev split: 0 examples [00:00, ? examples/s]

Generating devtest split: 0 examples [00:00, ? examples/s]

In [40]:
import random

# Set random seed
random.seed(50)

# Get sentences in both languages
thai_text = dataset['dev']['sentence_tha_Thai']
english_text = dataset['dev']['sentence_eng_Latn']

# Make pairs and select 100 random ones
all_pairs = list(zip(thai_text, english_text))
random_pairs = random.sample(all_pairs, 100)

# Show all pairs
for num, (thai, eng) in enumerate(random_pairs):
    print(f"\nPair {num + 1}")
    print(f"Thai: {thai}")
    print(f"English: {eng}")

Pair 0
Thai: นี่ไม่ใช่กลุ่มอาการขาดทักษะด้านการเรียนรู้ แต่เป็นความผิดปกติทางการเรียนรู้ โรคนี้ "ส่งผลกระทบต่อเด็กร้อยละ 3 ถึง 5 ซึ่งอาจเป็นเด็กอเมริกันมากถึง 2 ล้านคน"
English: It is not a learning disability, it is a learning disorder; it "affects 3 to 5 percent of all children, perhaps as many as 2 million American children".

Pair 1
Thai: ผู้ที่ไม่คุ้นเคยกับศัพท์เฉพาะทางการแพทย์คิดว่า คำว่าติดเชื้อและโรคติดต่อนั้นมีความหมายต่างกัน
English: For those unfamiliar with medical jargon, the words infectious and contagious have distinct meanings.

Pair 2
Thai: เขาตั้งข้อสังเกตว่า งานวิจัยบางชิ้นชี้ให้เห็นว่าโรคนี้จำเป็นต้องมีอันตรายน้อยลงก่อนที่มันจะแพร่ระบาดไปทั่วโลก
English: Some studies suggest that the disease must become less lethal before it can cause a global epidemic, he noted.

Pair 3
Thai: นักวิทยาศาสตร์รายอื่น ๆ แย้งว่าพืชเหล่านี้มีพิษร้ายแรง จึงไม่น่าเป็นไปได้ที่จะมีไดโนเสาร์ตัวใดกินพวกมันได้ แม้ว่าในปัจจุบันสลอธและสัตว์อื่น ๆ เช่น นกแก้ว (ลูกหลานของไดโนเสาร์) จะสามารถกินใบไม้หรือผลไม้มีพิษได้ก็ตาม
English: Other scientists argue that these plants are very poisonous so it is unlikely that any dinosaur ate them, even though today the sloth and other animals like the parrot (a descendant of the dinosaurs) can eat poisonous leaves or fruit.

Pair 4
Thai: ถึงแม้คุณอาจเคยได้ยินชาวกรีนแลนด์ใช้คำนี้ แต่ชาวต่างชาติไม่ควรใช้
English: While you may hear the word used by Greenlandic Natives, its use should be avoided by foreigners.

Pair 5
Thai: นอกจากนี้ยังไม่มีข้อกำหนดว่าคุณจะต้องwfhรับหมายเลขท้องถิ่นจากชุมชนที่คุณอาศัยอยู่ คุณสามารถรับการเชื่อมต่ออินเทอร์เน็ตผ่านดาวเทียมในชิกเก้นซึ่งเป็นเมืองที่ห่างไกลความเจริญในอลาสก้า และเลือกหมายเลขที่บ่งบอกว่าคุณอยู่ในแอริโซนาที่มีแสงแดดจ้า
English: There is also no requirement that you obtain a local number from the community in which you live; you can obtain a satellite Internet connection in the wilds of Chicken, Alaska and select a number which claims you're in sunny Arizona.

Pair 6
Thai: โฮสเทลแห่งหนึ่งถล่มในเมกกะซึ่งเป็นเมืองศักดิ์สิทธิ์ของศาสนาอิสลามเมื่อเวลาประมาณ 10 นาฬิกาของเช้าวันนี้ตามเวลาท้องถิ่น
English: A hostel collapsed in Mecca, the holy city of Islam at about 10 o'clock this morning local time.

Pair 7
Thai: ถึงอย่างนั้นก็คาดได้เลยว่าจะต้องหายใจหอบ และต้องระวังในส่วนที่ลาดชันกว่าโดยเฉพาะเมื่อเปียก เนื่องจากอาจเกิดอันตรายได้อย่างรวดเร็ว
English: That said, expect to be out of breath, and take care in the steeper portions, especially when wet, as it can become dangerous quickly.

Pair 8
Thai: ความเชื่อทางไสยศาสตร์สามารถจำแนกออกจากรูปแบบความเชื่อทางศาสนาและการบูชาอื่น ๆ ด้วยลักษณะที่เน้นในเรื่องประสบการณ์ตรงของการตระหนักรู้ในภาวะต่าง ๆ โดยเฉพาะภาวะของความรู้สึกสงบ การหยั่งรู้ ความผาสุก หรือแม้แต่ความปิติยินดีเหลือล้น
English: Mysticism can be distinguished from other forms of religious belief and worship by its emphasis on the direct personal experience of a unique state of consciousness, particularly those of a peaceful, insightful, blissful, or even ecstatic character.

Pair 9
Thai: สัตว์ป่าอาจขี้อายหรือก้าวร้าวก็ได้ สภาพแวดล้อมอาจเย็น ร้อน หรือยากลำบาก
English: Wild animals might either be shy or aggressive. The environment might be cold, hot, or otherwise hostile.

Pair 10
Thai: ปีเตอร์ เลนซ์ นักแข่งรถมอเตอร์ไซค์วัย 13 ปี เสียชีวิตหลังจากอยู่ในอุบัติเหตุรถชนกันที่อินเดียนาโปลิสมอเตอร์สปีดเวย์
English: Peter Lenz, a 13-year-old motorcycle racer, has died after being involved in a crash at the Indianapolis Motor Speedway.

Pair 11
Thai: ข่าวแพร่สะพัดในชุมชนเรดเลคในวันนี้ว่ามีนักเรียนอีกคนถูกจับุมจากการก่อเหตุกราดยิงในโรงเรียนเมื่อวันที่ 21 มีนาคม ขณะที่งานศพของ Jeff Weise และเหยื่อ 3 ใน 9 คนดำเนินอยู่
English: News spread in the Red Lake community today as funerals for Jeff Weise and three of the nine victims were held that another student was arrested in connection with the school shootings of March 21.

Pair 12
Thai: การปฏิบัติตามหลักการโภชนาการที่เหมาะสมแค่อย่างเดียวไม่สามารถช่วยให้เกิดสมรรถภาพระดับดีเลิศได้ แต่อาจส่งผลอย่างมากต่อสุขภาพโดยรวมของนักกีฬารุ่นเยาว์
English: Proper nutritional practices alone cannot generate elite performances, but they can significantly affect young athletes' overall wellness.

Pair 13
Thai: พายุลูกนี้อยู่ห่างจากเมืองไมอามี่ในรัฐฟลอริดาราว 3,000 ไมล์โดยมีแรงลมสูงสุดอยู่ที่ 40 ไมล์/ชม. (64 กม./ชม.)
English: The storm, located approximately 3,000 miles from Miami, Florida, has maximum sustained winds of 40 mph (64 kph).

Pair 14
Thai: ทฤษฎีนี้ย้อนแย้งกับคำกล่าวอ้างที่ว่า ดวงจันทร์นั้นไม่มีความเคลื่อนไหวทางธรณีวิทยาเลยแม้แต่น้อย
English: This theory contradicts the claim that the moon is completely devoid of geologic activity.

Pair 15
Thai: การเข้าวัดจะต้องใช้บัตร Angkor Pass ดังนั้นเมื่อจะเดินทางไปโตนเลสาบ โปรดอย่าลืมนำหนังสือเดินทางติดตัวไปด้วย
English: The Angkor Pass is needed to enter the temple so do not forget to bring your passport along when heading to Tonle Sap.

Pair 16
Thai: เมื่อประชากรทั้งหมดมีลักษณะทางพันธุกรรมอย่างหนึ่งที่เหมือนกันก็จะถูกเรียกว่าโมโนมอร์ฟิก
English: When all individuals in a population are identical with regard to a particular phenotypic trait they are known as monomorphic.

Pair 17
Thai: ส่วนใหญ่แล้วจะเกิดขึ้นกับคนที่ทำงานเกี่ยวข้องกับสัตว์ปีกมากกว่า แต่นักดูนกก็มีความเสี่ยงเช่นกัน
English: Most have involved people who work with poultry, but there is also some risk to birdwatchers.

Pair 18
Thai: แม้คุณอาจจะคิดว่าเป็นเรื่องดีที่จะใช้บริการสายการบินเดิม ๆ ที่คุณบินด้วยบ่อยที่สุด แต่ควรทราบไว้ว่าสิทธิพิเศษที่แต่ละสายการบินมอบให้มักจะแตกต่างกัน และคะแนนไมล์สะสมของสายการบินอื่นในกลุ่มพันธมิตรเดียวกันอาจให้ผลตอบแทนที่เป็นประโยชน์มากกว่า
English: Although you may think it is intuitive to join the airline you fly most, you should be aware that privileges offered are often different and frequent flyer points may be more generous under a different airline in the same alliance.

Pair 19
Thai: หินบางชนิดที่หาได้ยากมากในโลก มีการขายตั้งแต่ราคา 11,000 ดอลลาร์สหรัฐไปจนถึง 22,500 ดอลลาร์สหรัฐต่อออนซ์ ซึ่งแพงกว่าราคาทองคำราวสิบเท่า
English: Some of the rocks, which are very rare on Earth, are being sold from US$11,000 to $22,500 per ounce, which is about ten times more than the cost of gold.

Pair 20
Thai: เนื่องจากด้านล่างของใบมีดโค้งเล็กน้อย เมื่อใบมีดเอียงไปด้านใดด้านหนึ่ง ขอบที่สัมผัสกับน้ำแข็งจึงโค้งเช่นกัน
English: Because the bottom of the blade is slightly curved, as the blade tilts to one side or the other, the edge which is in contact with the ice also curves.

Pair 21
Thai: อย่างไรก็ตาม ในปัจจุบันศิลปินกราฟฟิตีที่ได้รับการยอมรับ มีงานอีเวนต์กราฟฟิตี และกำแพง สำหรับวาดภาพกราฟฟิตีที่ "ถูกกฎหมาย" ภาพวาดกราฟฟิตีในบริบทนี้มักคล้ายกับงานศิลปะมากกว่าป้ายที่อ่านไม่ออก
English: However, nowadays there are established graffiti artists, graffiti events and "legal" walls. Graffiti paintings in this context often resemble artworks rather than illegible tags.

Pair 22
Thai: การที่วาล์วเปิดทำให้แรงดันถูกปล่อยออกจากระบบ แล้วน้ำมันก็ไหลไปตามรางสู่ถังที่มีความจุ 55,000 บาร์เรล (2.3 ล้านแกลลอน)
English: The valves opening allowed a pressure release for the system and oil flowed on a pad to a tank that can hold 55,000 barrels (2.3 million gallons).

Pair 23
Thai: ภาษาเสริมคือภาษาประดิษฐ์หรือภาษาที่สร้างขึ้นโดยมีวัตถุประสงค์เพื่ออำนวยความสะดวกในการสื่อสารระหว่างผู้คนที่อาจมีปัญหาในการสื่อสารหากไม่มีภาษานี้
English: Auxiliary languages are artificial or constructed languages created with the intent of facilitating communication between peoples who would otherwise have difficulty communicating.

Pair 24
Thai: โบเบ็ก เกิดในซาเกร็บซึ่งเป็นเมืองหลวงของโครเอเชียและมีชื่อเสียงขึ้นมาขณะเล่นให้กับปาร์ติซานเบลเกรด
English: Born in the Croatian capital, Zagreb, Bobek gained fame while playing for Partizan Belgrade.

Pair 25
Thai: นักวิทยาศาสตร์ได้ค้นพบรูปแบบของเปลือกโลกที่เรียกว่า lobate scarp กระจัดกระจายอยู่ทั่วพื้นผิวดวงจันทร์ ซึ่งปรากฏว่าเป็นผลมาจากการที่ดวงจันทร์หดตัวช้ามาก
English: Scientists have discovered landforms littered across the moon's surface called lobate scarps that have apparently resulted from the moon's shrinking very slowly.

Pair 26
Thai: ชูมัคเกอร์ซึ่งเกษียณในปี 2006 หลังจากที่คว้าแชมป์ฟอร์มูล่าวันไปเจ็ดครั้ง ต้องเข้ามาทำหน้าที่แทนเฟลิเป้ มาสซาซึ่งได้รับบาดเจ็บ
English: Schumacher who retired in 2006 after winning the Formula 1 championship seven times, was due to replace the injured Felipe Massa.

Pair 27
Thai: HK Management Inc. ซึ่งเป็นบริษัทจัดการของวงไม่ได้ให้เหตุผลเบื้องต้นตอนที่พวกเขายกเลิกในวันที่ 20 กันยายน แต่วันรุ่งขึ้นก็กล่าวโทษเหตุผลที่มีตรรกะต่าง ๆ
English: The band's management company, HK Management Inc., gave no initial reason when they canceled on September 20, but blamed logistical reasons by the next day.

Pair 28
Thai: มีค่าธรรมเนียมเพิ่มเติมสำหรับการเดินทางโดยมีผู้โดยสารมากกว่า 2 คน ตัวเลือกนี้จึงอาจมีราคาแพงกว่าที่จำเป็น
English: There is a surcharge for having more than 2 passengers, so this option might be more expensive than necessary.

Pair 29
Thai: กลุ่มเต้นรำ Fire of Anatolia ของตุรกี ได้แสดงการเต้นรำชุด "Troy" เพื่อจบการแสดง
English: To finish, Turkish dance group Fire of Anatolia performed the show "Troy".

Pair 30
Thai: บุคคลที่มีส่วนเกี่ยวข้องมาหลายสิบปีช่วยให้เราชื่นชมจุดแข็งและความหลงใหลของตัวเอง พร้อมทั้งประเมินความยากลำบากและกระทั่งความล้มเหลวอย่างตรงไปตรงมาในขณะเดียวกัน
English: Individuals who had been involved for several decades helped us appreciate our strengths and passions while candidly assessing difficulties and even failures.

Pair 31
Thai: แอปแปลข้อความตามเวลาจริง - แอปพลิเคชั่นที่สามารถแปลข้อความทั้งส่วนจากภาษาหนึ่งเป็นอีกภาษาได้โดยอัตโนมัติ
English: Real-time text translator apps – applications that are capable of automatically translating whole segments of text from one language into another.

Pair 32
Thai: ในกรณีนี้ การนึกถึงตัวอย่างพฤติกรรมแบบผู้บริหารและผลลัพธ์ความสำเร็จที่ตามมาช่วยให้ผู้คนเปิดรับความเปลี่ยนแปลงและแนวทางใหม่ๆ สำหรับคริสตจักรในท้องถิ่น
English: In this instance, recalling previous instances of entrepreneurial behavior and resulting successes helped people to be open to new changes and new direction for the local church.

Pair 33
Thai: หลังจากเกิดเพลิงไหม้ ป้อมปราการได้รับการอนุรักษ์และปกป้อง และยังคงเป็นสถานที่ท่องเที่ยวที่น่าตื่นตาตื่นใจที่สุดแห่งหนึ่งของภูฏาน
English: After the fire, the fortress was preserved and protected, remaining to be one of Bhutan's most sensational attractions.

Pair 34
Thai: โรงแรมหรือเจ้าบ้านของคุณ (กรณีที่คุณพักในเกสต์เฮาส์หรือบ้านส่วนตัว) มักจะมี wifi หรือคอมพิวเตอร์ที่ต่อกับอินเทอร์เน็ต และทุกชุมชนจะมีร้านอินเทอร์เน็ตหรือบางที่ก็มี wifi สาธารณะ
English: Your hotel or hosts (if staying in a guesthouse or private home) will likely have wifi or an internet connected PC, and all settlements have an internet cafe or some location with public wifi.

Pair 35
Thai: Lodin ยังกล่าวอีกว่าเจ้าหน้าที่ตัดสินใจยกเลิกการเลือกตั้งซ้ำเพื่อเป็นการประหยัดค่าใช้จ่ายและป้องกันความเสี่ยงด้านความปลอดภัยของการเลือกตั้งอื่นให้กับชาวอัฟกานิสถาน
English: Lodin also said officials decided to cancel the runoff in order to save Afghans the expense and security risk of another election.

Pair 36
Thai: ในบางประเทศที่มีรัฐบาลกลาง เช่น สหรัฐอเมริกา และแคนาดา จะมีการเรียกเก็บภาษีเงินได้ทั้งในระดับรัฐบาลกลางและในระดับท้องถิ่น ด้วยเหตุนี้ อัตราและขั้นภาษีอาจแตกต่างกันไปในแต่ละภูมิภาค
English: In some federal countries, such as the United States and Canada, income tax is levied both at the federal level and at the local level, so the rates and brackets can vary from region to region.

Pair 37
Thai: โดยทั่วไปคุณจะต้องประกาศการให้ความช่วยเหลือของคุณ เดินไปตามท่าเรือ เข้าหาผู้คนที่กำลังทำความสะอาดเรือยอตช์ พยายามติดต่อกับกะลาสีเรือในบาร์ และอื่น ๆ
English: Basically you'll be putting up notices offering your help, pacing the docks, approaching people cleaning their yachts, trying to make contact with sailors in the bar, etc.

Pair 38
Thai: ผู้ประท้วงหวังจะรวบรวมรายชื่อผู้ร้องเรียนได้ถึง 1.2 ล้านรายชื่อเพื่อเสนอต่อสภาคองเกรสในเดือนพฤศจิกายน
English: Protesters hope to collect a petition of 1.2 million signatures to present to the National Congress in November.

Pair 39
Thai: ธารน้ำแข็งไม่จับตัวแข็งมากนัก แต่มันไหลลงไปตามภูเขา ซึ่งเป็นสาเหตุของรอยแตกและรอยแยกของน้ำแข็งบนภูเขา ซึ่งอาจจะถูกสะพานหิมะปกคลุมไว้
English: The glaciers are not stable, but flow down the mountain. This will cause cracks, crevasses, which may be obscured by snow bridges.

Pair 40
Thai: Cinque Terre ซึ่งหมายความว่าห้าดินแดน ประกอบด้วยหมู่บ้านชายฝั่งห้าหมู่บ้าน ได้แก่ Riomaggiore, Manarola, Corniglia, Vernazza และ Monterosso ซึ่งตั้งอยู่ในแคว้น Liguria ประเทศอิตาลี
English: Cinque Terre, which means Five Lands, comprises the five small coastal villages of Riomaggiore, Manarola, Corniglia, Vernazza and Monterosso located in the Italian region of Liguria.

Pair 41
Thai: แม้จะยังไม่ถึงขั้นเป็นปรากฏการณ์แห่งโลกยุคใหม่ แต่คนส่วนใหญ่ก็อาจเชื่อมโยงสิ่งนี้กับเยาวชนที่ใช้สีสเปรย์ฉีดทำลายทรัพย์สินสาธารณะและทรัพย์สินส่วนบุคคล
English: While it's far from a modern phenomenon, most people probably associate it with youth vandalizing public and private property using spray paint.

Pair 42
Thai: เรามีวิกฤตการณ์ทางการเงินตลอดทั้งปี ซึ่งเป็นช่วงเวลาที่เลวร้ายที่สุดในช่วงสองเดือนที่ผ่านมา และผมคิดว่าตอนนี้ตลาดการเงินกำลังเริ่มฟื้นตัวแล้ว "
English: We have a year-long financial crisis, which has had its most acute moment in the past two months, and I think now the financial markets are beginning to recover."

Pair 43
Thai: การเดินป่าในช่วงกลางวันมีตั้งแต่ระยะทางน้อยกว่าหนึ่งไมล์ไปจนถึงระยะทางไกลกว่าซึ่งสามารถเดินได้จบได้ในวันเดียว
English: Day hiking involves distances of less than a mile up to longer distances that can be covered in a single day.

Pair 44
Thai: อาจดูน่ากลัวเล็กน้อยเมื่อมองจากด้านล่างและเป็นทางขึ้นที่สูงชันและยากลำบาก แต่คนส่วนใหญ่ที่แข็งแรงพอควรจะขึ้นไปได้สำเร็จภายในเวลาประมาณ 45 นาที
English: It looks a bit daunting from below, and it is a steep and difficult ascent, but most reasonably fit persons should be able to make it in about 45 minutes.

Pair 45
Thai: ในช่วงฤดูร้อนต้องระวังยุงนอร์ดิกด้วย แม้ว่าพวกมันจะไม่ได้นำโรคใด ๆ แต่ก็อาจทำให้ระคายเคืองได้
English: During the summer, also watch out for the Nordic mosquitoes. Although they do not transmit any diseases, they can be irritating.

Pair 46
Thai: สถานที่หลายแห่งในโรโตรัวมีแฮงงิที่ทำจากพลังงานความร้อนใต้พิภพในขณะที่ แฮงงิประเภทอื่น ๆ จะสามารถลิ้มลองได้ในไครสต์เชิร์ช เวลลิงตัน และเมืองอื่น ๆ
English: Several places in Rotorua offer geothermal hangi, while other hangi can be sampled in Christchurch, Wellington and elsewhere.

Pair 47
Thai: ในศตวรรษที่ 18 กัมพูชารู้สึกว่าตนเองเปรียบเสมือนหญ้าแห้งที่อยู่ตรงกลางระหว่างช้างสองตัว คือ ประเทศไทยกับเวียดนาม
English: During the 18th century Cambodia found itself squeezed between two powerful neighbors, Thailand and Vietnam.

Pair 48
Thai: วิดัลวัย 28 ปี ย้ายจากเซบีญ่ามาเข้าร่วมกับบาร์ซ่าเมื่อสามฤดูกาลก่อน
English: 28-year-old Vidal had joined Barça three seasons ago, from Sevilla.

Pair 49
Thai: เจ้าหน้าที่ยังไม่รู้ชื่อของเขา รู้เพียงว่าเขาเป็นสมาชิกของกลุ่มชาติพันธุ์อุยกูร์
English: His name is still unknown to authorities, although they do know he is a member of the Uighur ethnic group.

Pair 50
Thai: โชคดีที่ฉันไม่เป็นอะไร แต่ก็ต้องเจอกับเหตุการณ์ขวัญผวาที่ได้เห็นผู้คนกำลังพยายามทุบทำลายหน้าต่างเพื่อหนีตายออกมาข้างนอก
English: "Luckily nothing happened to me, but I saw a macabre scene, as people tried to break windows in order to get out.

Pair 51
Thai: มีเพียงไม่กี่สายการบินเท่านั้นที่ยังคงเสนอค่าโดยสารเพื่อเยียวยาการสูญเสียที่จะช่วยลดค่าโดยสารเล็กน้อยให้ผู้ที่ต้องการเดินทางไปเข้าร่วมพิธีศพอย่างเร่งด่วน
English: Only a few airlines still offer bereavement fares, which slightly discount the cost of last-minute funeral travel.

Pair 52
Thai: เนื่องจากมีพื้นฐานมาจากการแข่งขัน Running Tours Barcelona ในเมืองบาร์เซโลนาและการแข่งขัน Running Copenhagen ในเมืองโคเปนเฮเกน จึงทำให้มีการนำการแข่งขัน Running Tours Prague ในกรุงปราก และการแข่งขันอื่น ๆ มาบรรจุอยู่ในเครือข่ายดังกล่าวอย่างรวดเร็ว
English: With roots in Barcelona's Running Tours Barcelona and Copenhagen's Running Copenhagen, it was quickly joined by Running Tours Prague based in Prague and others.

Pair 53
Thai: 2 ใน 3 ของชาวเวเนซุเอลาที่ทำงานทำงานในภาคบริการ เกือบ 1 ใน 4 ทำงานในภาคอุตสาหกรรม และ 1 ใน 5 ทำงานในภาคเกษตรกรรม
English: Two thirds of Venezuelans who work do so in the service sector, nearly a quarter work in industry and a fifth work in agriculture.

Pair 54
Thai: ก่อนที่ชาวสเปนจะมาที่นี่ในศตวรรษที่ 16 ตอนเหนือของชิลีอยู่ภายใต้การปกครองของจักรวรรดิอินคา ส่วนชนพื้นเมืองอาเรากานิอา (ชาวมาปูเช) อาศัยอยู่ในตอนกลางและตอนใต้ของชิลี
English: Before the Spanish arrived in the 16th century, northern Chile was under Inca rule while the indigenous Araucanians (Mapuche) inhabited central and southern Chile.

Pair 55
Thai: แคปซูลจะดูเหมือนดาวตกที่กำลังพุ่งข้ามฟากฟ้าอย่างมาก
English: The capsule will look much like a shooting star going across the sky.

Pair 56
Thai: ประมาณสิบนาทีก่อนถึงเวลาลงจอด เครื่องบินลำดังกล่าวหายไปเมื่อเข้าใกล้จุดหมายครั้งที่สอง
English: About ten minutes before it was due to land from its second approach it disapeared.

Pair 57
Thai: โดยทั่วไปแล้ว วีซ่านักเรียนจะมีข้อกำหนดและขั้นตอนการสมัครที่แตกต่างจากวีซ่านักท่องเที่ยวหรือวีซ่าธุรกิจแบบปกติ
English: Student visas generally have different requirements and application procedures from normal tourist or business visas.

Pair 58
Thai: การออกแบบเชิงโต้ตอบจำเป็นต้องให้ส่วนประกอบต่าง ๆ ของโปรเจ็กต์เชื่อมต่อกัน แต่ก็ใช้การได้ในฐานะเอนทิตีที่แยกต่างหากด้วยเช่นกัน
English: Interactive design requires that components of a project connect to each other, but also make sense as a separate entity.

Pair 59
Thai: มิตต์ รอมนี่ย์ (Mitt Romney) อดีตผู้ว่าการรัฐแมสซาชูเซตส์ชนะการเลือกตั้งขั้นต้นจากการลงชิงตำแหน่งประธานาธิบดีในนามพรรครีพับลิกันจากรัฐฟลอริดาเมื่อวันอังคารที่ผ่านมา ด้วยคะแนนเสียงมากกว่าร้อยละ 46
English: Former Massachusetts governor Mitt Romney won the Florida Republican Party presidential primary election on Tuesday with over 46 percent of the vote.

Pair 60
Thai: การบังคับโดรนให้บินใกล้ท่าอากาศยานหรือในฝูงชนแทบจะเป็นความคิดที่แย่อยู่เสมอ แม้ว่าการทำเช่นนี้จะไม่ผิดกฎหมายในพื้นที่ของคุณก็ตาม
English: Flying a drone near an airport or over a crowd is almost always a bad idea, even if it's not illegal in your area.

Pair 61
Thai: หากคุณต้องการบินรอบโลกในซีกโลกใต้อย่างสมบูรณ์ ตัวเลือกเที่ยวบินและจุดหมายปลายทางมีจำกัดเนื่องจากไม่มีเส้นทางที่ข้ามมหาสมุทร
English: If you want to fly around the world completely in the Southern Hemisphere, the choice of flights and destinations is limited due to the lack of transoceanic routes.

Pair 62
Thai: เซลล์เป็นหน่วยโครงสร้างที่มีหน้าที่ที่เล็กที่สุดของสิ่งมีชีวิต
English: A cell is the smallest structural and functional unit of a living (things) organism.

Pair 63
Thai: แนวคิดก็คือ ทุกประเทศในยุโรปต้องพยายามป้องกันไม่ให้ชาติใดชาติหนึ่งมีอำนาจเกินไป และด้วยเหตุนั้นรัฐบาลของชาติต่าง ๆ จึงมักสับเปลี่ยนพันธมิตรเพื่อรักษาสมดุลเอาไว้
English: The concept was that all European nations had to seek to prevent one nation from becoming powerful, and thus national governments often changed their alliances in order to maintain the balance.

Pair 64
Thai: เมืองนี้จะเป็นเมืองแรกในยุโรปตะวันออกเฉียงใต้ที่จัด CowParade ซึ่งเป็นงานศิลปะสาธารณะที่ใหญ่ที่สุดในโลก โดยจะจัดขึ้นในช่วงระหว่างเดือนมิถุนายนจนถึงสิงหาคมปีนี้
English: The city will be the first in southeastern Europe to host CowParade, the world's largest public art event, between June and August this year.

Pair 65
Thai: สเติร์นส์กำลังสืบสวนว่ามีการใช้ภาษีเพื่อสนับสนุนการทำแท้งผ่านองค์กร Planned Parenthood หรือไม่ ขณะที่สวมบทบาทประธานคณะอนุกรรมการกำกับดูแลและสืบสวน ซึ่งอยู่ภายใต้คณะกรรมาธิการพลังงานและการพาณิชย์
English: Stearns is investigating whether taxes are used to fund abortions through Planned Parenthood in his role as chairman of the Oversight and Investigations Subcommittee, which is under the umbrella of the House Energy and Commerce Committee.

Pair 66
Thai: ในปี พ.ศ. 2520 ดร.ดามาเดียนได้สร้างเครื่องสแกน MRI แบบ "ทั้งตัว" เป็นเครื่องแรก โดยเรียกมันว่า "เจ้าทรหดอดทน"

# **2. Machine Translation with Seq2Seq model (65 points, 20 points for each model, 5 points for data statistics)**

## **2.1 OPUS-MT**

In [41]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Get the Thai-to-English translation model
tokenizer = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-th-en")
model = AutoModelForSeq2SeqLM.from_pretrained("Helsinki-NLP/opus-mt-th-en")

# Simple translation function
def translate_thai(thai_text):
    tokens = tokenizer(thai_text, return_tensors="pt")
    result = model.generate(**tokens)
    return tokenizer.batch_decode(result, skip_special_tokens=True)[0]

# Go through each pair and translate
for i, (thai, eng) in enumerate(random_pairs):
    thai_translated = translate_thai(thai)
    print(f"\nSentence {i + 1}")
    print(f"Thai: {thai}")
    print(f"English (Original): {eng}")
    print(f"English (Translated): {thai_translated}")

Sentence 1:
Thai:       นี่ไม่ใช่กลุ่มอาการขาดทักษะด้านการเรียนรู้ แต่เป็นความผิดปกติทางการเรียนรู้ โรคนี้ "ส่งผลกระทบต่อเด็กร้อยละ 3 ถึง 5 ซึ่งอาจเป็นเด็กอเมริกันมากถึง 2 ล้านคน"
English:    It is not a learning disability, it is a learning disorder; it "affects 3 to 5 percent of all children, perhaps as many as 2 million American children".
Translated: This isn't a group of learning disability, it's a learning disorder, it's an effect on children from three to five, which is probably two million American children.

Sentence 2:
Thai:       ผู้ที่ไม่คุ้นเคยกับศัพท์เฉพาะทางการแพทย์คิดว่า คำว่าติดเชื้อและโรคติดต่อนั้นมีความหมายต่างกัน
English:    For those unfamiliar with medical jargon, the words infectious and contagious have distinct meanings.
Translated: Those who aren't familiar with medical terms think that infection and infectious diseases have different meanings.

Sentence 3:
Thai:       เขาตั้งข้อสังเกตว่า งานวิจัยบางชิ้นชี้ให้เห็นว่าโรคนี้จำเป็นต้องมีอันตรายน้อยลงก่อนที่มันจะแพร่ระบาดไปทั่วโลก
English:    Some studies suggest that the disease must become less lethal before it can cause a global epidemic, he noted.
Translated: He noted that some of the research suggests that it needs to be less dangerous before it spreads around the world.

Sentence 4:
Thai:       นักวิทยาศาสตร์รายอื่น ๆ แย้งว่าพืชเหล่านี้มีพิษร้ายแรง จึงไม่น่าเป็นไปได้ที่จะมีไดโนเสาร์ตัวใดกินพวกมันได้ แม้ว่าในปัจจุบันสลอธและสัตว์อื่น ๆ เช่น นกแก้ว (ลูกหลานของไดโนเสาร์) จะสามารถกินใบไม้หรือผลไม้มีพิษได้ก็ตาม
English:    Other scientists argue that these plants are very poisonous so it is unlikely that any dinosaur ate them, even though today the sloth and other animals like the parrot (a descendant of the dinosaurs) can eat poisonous leaves or fruit.
Translated: Other scientists argue that these plants are so toxic that there's no possibility that a dinosaur could eat them, although now Sloth and other animals, such as parrots, can eat leaves or poisonous fruit.

Sentence 5:
Thai:       ถึงแม้คุณอาจเคยได้ยินชาวกรีนแลนด์ใช้คำนี้ แต่ชาวต่างชาติไม่ควรใช้
English:    While you may hear the word used by Greenlandic Natives, its use should be avoided by foreigners.
Translated: Although you've probably heard of Greenlanders using that word, foreigners shouldn't use it.

Sentence 6:
Thai:       นอกจากนี้ยังไม่มีข้อกำหนดว่าคุณจะต้องwfhรับหมายเลขท้องถิ่นจากชุมชนที่คุณอาศัยอยู่ คุณสามารถรับการเชื่อมต่ออินเทอร์เน็ตผ่านดาวเทียมในชิกเก้นซึ่งเป็นเมืองที่ห่างไกลความเจริญในอลาสก้า และเลือกหมายเลขที่บ่งบอกว่าคุณอยู่ในแอริโซนาที่มีแสงแดดจ้า
English:    There is also no requirement that you obtain a local number from the community in which you live; you can obtain a satellite Internet connection in the wilds of Chicken, Alaska and select a number which claims you're in sunny Arizona.
Translated: There is no policy that you need to wffth to get local numbers from the community you live in, you can get Internet connections in Chicken, a remote town in Alaska, and pick numbers that indicate that you're in Arizona with bright sunlight.

Sentence 7:
Thai:       โฮสเทลแห่งหนึ่งถล่มในเมกกะซึ่งเป็นเมืองศักดิ์สิทธิ์ของศาสนาอิสลามเมื่อเวลาประมาณ 10 นาฬิกาของเช้าวันนี้ตามเวลาท้องถิ่น
English:    A hostel collapsed in Mecca, the holy city of Islam at about 10 o'clock this morning local time.
Translated: One of the Hostels collapsed in Megka, the holy city of Islam at about 10 o'clock in the morning, at local time.

Sentence 8:
Thai:       ถึงอย่างนั้นก็คาดได้เลยว่าจะต้องหายใจหอบ และต้องระวังในส่วนที่ลาดชันกว่าโดยเฉพาะเมื่อเปียก เนื่องจากอาจเกิดอันตรายได้อย่างรวดเร็ว
English:    That said, expect to be out of breath, and take care in the steeper portions, especially when wet, as it can become dangerous quickly.
Translated: Even so, it's expected to take a breath, and be careful of the steeper slopes, especially when we're wet, because they can be dangerous very quickly.

Sentence 9:
Thai:       ความเชื่อทางไสยศาสตร์สามารถจำแนกออกจากรูปแบบความเชื่อทางศาสนาและการบูชาอื่น ๆ ด้วยลักษณะที่เน้นในเรื่องประสบการณ์ตรงของการตระหนักรู้ในภาวะต่าง ๆ โดยเฉพาะภาวะของความรู้สึกสงบ การหยั่งรู้ ความผาสุก หรือแม้แต่ความปิติยินดีเหลือล้น
English:    Mysticism can be distinguished from other forms of religious belief and worship by its emphasis on the direct personal experience of a unique state of consciousness, particularly those of a peaceful, insightful, blissful, or even ecstatic character.
Translated: Hypocrisy can distinguish from religious and other religious forms of worship, with a feature that focuses on the accurate experience of awareness of conditions, especially the state of feeling calm, perception, joy, even extremism.

Sentence 10:
Thai:       สัตว์ป่าอาจขี้อายหรือก้าวร้าวก็ได้ สภาพแวดล้อมอาจเย็น ร้อน หรือยากลำบาก
English:    Wild animals might either be shy or aggressive. The environment might be cold, hot, or otherwise hostile.
Translated: The animal may be shy or aggressive, its environment may be cold, hot, or difficult.

Sentence 11:
Thai:       ปีเตอร์ เลนซ์ นักแข่งรถมอเตอร์ไซค์วัย 13 ปี เสียชีวิตหลังจากอยู่ในอุบัติเหตุรถชนกันที่อินเดียนาโปลิสมอเตอร์สปีดเวย์
English:    Peter Lenz, a 13-year-old motorcycle racer, has died after being involved in a crash at the Indianapolis Motor Speedway.
Translated: Peter Lance, a 13-year-old motorcycle racer, died after a car crash in Indianapolis, a speedway motor.

Sentence 12:
Thai:       ข่าวแพร่สะพัดในชุมชนเรดเลคในวันนี้ว่ามีนักเรียนอีกคนถูกจับุมจากการก่อเหตุกราดยิงในโรงเรียนเมื่อวันที่ 21 มีนาคม ขณะที่งานศพของ Jeff Weise และเหยื่อ 3 ใน 9 คนดำเนินอยู่
English:    News spread in the Red Lake community today as funerals for Jeff Weise and three of the nine victims were held that another student was arrested in connection with the school shootings of March 21.
Translated: The news spread in the Red Lake community today that another student was caught in a shooting in the school on March 21st, while Jeff Weise's funeral and 3 of the 9 victims were on the run.

Sentence 13:
Thai:       การปฏิบัติตามหลักการโภชนาการที่เหมาะสมแค่อย่างเดียวไม่สามารถช่วยให้เกิดสมรรถภาพระดับดีเลิศได้ แต่อาจส่งผลอย่างมากต่อสุขภาพโดยรวมของนักกีฬารุ่นเยาว์
English:    Proper nutritional practices alone cannot generate elite performances, but they can significantly affect young athletes' overall wellness.
Translated: Following just the right nutrition can't help to achieve excellent performance, but it can have a huge impact on the overall health of young athletes.

Sentence 14:
Thai:       พายุลูกนี้อยู่ห่างจากเมืองไมอามี่ในรัฐฟลอริดาราว 3,000 ไมล์โดยมีแรงลมสูงสุดอยู่ที่ 40 ไมล์/ชม. (64 กม./ชม.)
English:    The storm, located approximately 3,000 miles from Miami, Florida, has maximum sustained winds of 40 mph (64 kph).
Translated: This storm is 3,000 miles from Miami in Florida with the highest wind at 40 miles per hour.

Sentence 15:
Thai:       ทฤษฎีนี้ย้อนแย้งกับคำกล่าวอ้างที่ว่า ดวงจันทร์นั้นไม่มีความเคลื่อนไหวทางธรณีวิทยาเลยแม้แต่น้อย
English:    This theory contradicts the claim that the moon is completely devoid of geologic activity.
Translated: This theory contradicts the claim that the moon has no geological movement at all.

Sentence 16:
Thai:       การเข้าวัดจะต้องใช้บัตร Angkor Pass ดังนั้นเมื่อจะเดินทางไปโตนเลสาบ โปรดอย่าลืมนำหนังสือเดินทางติดตัวไปด้วย
English:    The Angkor Pass is needed to enter the temple so do not forget to bring your passport along when heading to Tonle Sap.
Translated: The measurement is required to use the Angkor Pass card, so on your way to Tonleucation, please remember to take your passport with you.

Sentence 17:
Thai:       เมื่อประชากรทั้งหมดมีลักษณะทางพันธุกรรมอย่างหนึ่งที่เหมือนกันก็จะถูกเรียกว่าโมโนมอร์ฟิก
English:    When all individuals in a population are identical with regard to a particular phenotypic trait they are known as monomorphic.
Translated: When the entire population has a genetic trait, it's called monomorphic.

Sentence 18:
Thai:       ส่วนใหญ่แล้วจะเกิดขึ้นกับคนที่ทำงานเกี่ยวข้องกับสัตว์ปีกมากกว่า แต่นักดูนกก็มีความเสี่ยงเช่นกัน
English:    Most have involved people who work with poultry, but there is also some risk to birdwatchers.
Translated: Most of the time, it happens to people who work with birds, but it's also at risk.

Sentence 19:
Thai:       แม้คุณอาจจะคิดว่าเป็นเรื่องดีที่จะใช้บริการสายการบินเดิม ๆ ที่คุณบินด้วยบ่อยที่สุด แต่ควรทราบไว้ว่าสิทธิพิเศษที่แต่ละสายการบินมอบให้มักจะแตกต่างกัน และคะแนนไมล์สะสมของสายการบินอื่นในกลุ่มพันธมิตรเดียวกันอาจให้ผลตอบแทนที่เป็นประโยชน์มากกว่า
English:    Although you may think it is intuitive to join the airline you fly most, you should be aware that privileges offered are often different and frequent flyer points may be more generous under a different airline in the same alliance.
Translated: Although you may think it's a good thing to use the same airline as you do most of the time, it's good to know that the privilege that each airline offers is often different and that the score of miles of other airlines in the same group may be more beneficial.

Sentence 20:
Thai:       หินบางชนิดที่หาได้ยากมากในโลก มีการขายตั้งแต่ราคา 11,000 ดอลลาร์สหรัฐไปจนถึง 22,500 ดอลลาร์สหรัฐต่อออนซ์ ซึ่งแพงกว่าราคาทองคำราวสิบเท่า
English:    Some of the rocks, which are very rare on Earth, are being sold from US$11,000 to $22,500 per ounce, which is about ten times more than the cost of gold.
Translated: Some of the most rare stones in the world are sold from $11,000 to 22,500 per ounce, which is about ten times the price of gold.

Sentence 21:
Thai:       เนื่องจากด้านล่างของใบมีดโค้งเล็กน้อย เมื่อใบมีดเอียงไปด้านใดด้านหนึ่ง ขอบที่สัมผัสกับน้ำแข็งจึงโค้งเช่นกัน
English:    Because the bottom of the blade is slightly curved, as the blade tilts to one side or the other, the edge which is in contact with the ice also curves.
Translated: Because the bottom of the blade is slightly curved, when the blade is tilted to either side, the edge that touches the ice is also curved.

Sentence 22:
Thai:       อย่างไรก็ตาม ในปัจจุบันศิลปินกราฟฟิตีที่ได้รับการยอมรับ มีงานอีเวนต์กราฟฟิตี และกำแพง สำหรับวาดภาพกราฟฟิตีที่ "ถูกกฎหมาย" ภาพวาดกราฟฟิตีในบริบทนี้มักคล้ายกับงานศิลปะมากกว่าป้ายที่อ่านไม่ออก
English:    However, nowadays there are established graffiti artists, graffiti events and "legal" walls. Graffiti paintings in this context often resemble artworks rather than illegible tags.
Translated: Now, however, the respected graphic artist has a fair event and a wall for drawing graphics at "lawful," a graphic picture in this context that is much more like an unreadable piece of art.

Sentence 23:
Thai:       การที่วาล์วเปิดทำให้แรงดันถูกปล่อยออกจากระบบ แล้วน้ำมันก็ไหลไปตามรางสู่ถังที่มีความจุ 55,000 บาร์เรล (2.3 ล้านแกลลอน)
English:    The valves opening allowed a pressure release for the system and oil flowed on a pad to a tank that can hold 55,000 barrels (2.3 million gallons).
Translated: The valve releases the pressure from the system, and then the oil leads to a tank with 55,000 barrels (.3 million gallons) in it.

Sentence 24:
Thai:       ภาษาเสริมคือภาษาประดิษฐ์หรือภาษาที่สร้างขึ้นโดยมีวัตถุประสงค์เพื่ออำนวยความสะดวกในการสื่อสารระหว่างผู้คนที่อาจมีปัญหาในการสื่อสารหากไม่มีภาษานี้
English:    Auxiliary languages are artificial or constructed languages created with the intent of facilitating communication between peoples who would otherwise have difficulty communicating.
Translated: It's an artificial language or a language built on purpose to accommodate communication between people who might have trouble communicating without it.

Sentence 25:
Thai:       โบเบ็ก เกิดในซาเกร็บซึ่งเป็นเมืองหลวงของโครเอเชียและมีชื่อเสียงขึ้นมาขณะเล่นให้กับปาร์ติซานเบลเกรด
English:    Born in the Croatian capital, Zagreb, Bobek gained fame while playing for Partizan Belgrade.
Translated: Bobek was born in Salem, which is the capital of Croatia and is famous for playing for the Partisan Belgrade.

Sentence 26:
Thai:       นักวิทยาศาสตร์ได้ค้นพบรูปแบบของเปลือกโลกที่เรียกว่า lobate scarp กระจัดกระจายอยู่ทั่วพื้นผิวดวงจันทร์ ซึ่งปรากฏว่าเป็นผลมาจากการที่ดวงจันทร์หดตัวช้ามาก
English:    Scientists have discovered landforms littered across the moon's surface called lobate scarps that have apparently resulted from the moon's shrinking very slowly.
Translated: Scientists have discovered a form of Earth's crust called the Lobeate Scar, scattered all over the surface of the moon, which appears to be the result of the very slow shrink of the moon.

Sentence 27:
Thai:       ชูมัคเกอร์ซึ่งเกษียณในปี 2006 หลังจากที่คว้าแชมป์ฟอร์มูล่าวันไปเจ็ดครั้ง ต้องเข้ามาทำหน้าที่แทนเฟลิเป้ มาสซาซึ่งได้รับบาดเจ็บ
English:    Schumacher who retired in 2006 after winning the Formula 1 championship seven times, was due to replace the injured Felipe Massa.
Translated: Schumacher, retired in 2006, after seven arrests of Formula Day, had to take over the injured Felicia Massa.

Sentence 28:
Thai:       HK Management Inc. ซึ่งเป็นบริษัทจัดการของวงไม่ได้ให้เหตุผลเบื้องต้นตอนที่พวกเขายกเลิกในวันที่ 20 กันยายน แต่วันรุ่งขึ้นก็กล่าวโทษเหตุผลที่มีตรรกะต่าง ๆ
English:    The band's management company, HK Management Inc., gave no initial reason when they canceled on September 20, but blamed logistical reasons by the next day.
Translated: HK Management Inc., which is a band management company, doesn't give them a preliminary reason when they cancel September 20th, but the next day, they blame them for various reasons.

Sentence 29:
Thai:       มีค่าธรรมเนียมเพิ่มเติมสำหรับการเดินทางโดยมีผู้โดยสารมากกว่า 2 คน ตัวเลือกนี้จึงอาจมีราคาแพงกว่าที่จำเป็น
English:    There is a surcharge for having more than 2 passengers, so this option might be more expensive than necessary.
Translated: With more than two passengers, this option may be more expensive than necessary.

Sentence 30:
Thai:       กลุ่มเต้นรำ Fire of Anatolia ของตุรกี ได้แสดงการเต้นรำชุด "Troy" เพื่อจบการแสดง
English:    To finish, Turkish dance group Fire of Anatolia performed the show "Troy".
Translated: The Fire of Antarctica dances of Turkey have performed a series of "Troy" dances to end the show.

Sentence 31:
Thai:       บุคคลที่มีส่วนเกี่ยวข้องมาหลายสิบปีช่วยให้เราชื่นชมจุดแข็งและความหลงใหลของตัวเอง พร้อมทั้งประเมินความยากลำบากและกระทั่งความล้มเหลวอย่างตรงไปตรงมาในขณะเดียวกัน
English:    Individuals who had been involved for several decades helped us appreciate our strengths and passions while candidly assessing difficulties and even failures.
Translated: Those who have been involved for decades have helped us to appreciate our strengths and our passions, with a straightforward assessment of our difficulties and even our failures at the same time.

Sentence 32:
Thai:       แอปแปลข้อความตามเวลาจริง - แอปพลิเคชั่นที่สามารถแปลข้อความทั้งส่วนจากภาษาหนึ่งเป็นอีกภาษาได้โดยอัตโนมัติ
English:    Real-time text translator apps – applications that are capable of automatically translating whole segments of text from one language into another.
Translated: Activating message at real time - apps can automatically translate text from one language into another.

Sentence 33:
Thai:       ในกรณีนี้ การนึกถึงตัวอย่างพฤติกรรมแบบผู้บริหารและผลลัพธ์ความสำเร็จที่ตามมาช่วยให้ผู้คนเปิดรับความเปลี่ยนแปลงและแนวทางใหม่ๆ สำหรับคริสตจักรในท้องถิ่น
English:    In this instance, recalling previous instances of entrepreneurial behavior and resulting successes helped people to be open to new changes and new direction for the local church.
Translated: In this case, thinking about the example of executive behavior and success that comes from helping people to embrace new changes and ways for local churches.

Sentence 34:
Thai:       หลังจากเกิดเพลิงไหม้ ป้อมปราการได้รับการอนุรักษ์และปกป้อง และยังคงเป็นสถานที่ท่องเที่ยวที่น่าตื่นตาตื่นใจที่สุดแห่งหนึ่งของภูฏาน
English:    After the fire, the fortress was preserved and protected, remaining to be one of Bhutan's most sensational attractions.
Translated: After the fire, the fortress was preserved and protected, and it was still one of the most amazing sights of the Bhutan.

Sentence 35:
Thai:       โรงแรมหรือเจ้าบ้านของคุณ (กรณีที่คุณพักในเกสต์เฮาส์หรือบ้านส่วนตัว) มักจะมี wifi หรือคอมพิวเตอร์ที่ต่อกับอินเทอร์เน็ต และทุกชุมชนจะมีร้านอินเทอร์เน็ตหรือบางที่ก็มี wifi สาธารณะ
English:    Your hotel or hosts (if staying in a guesthouse or private home) will likely have wifi or an internet connected PC, and all settlements have an internet cafe or some location with public wifi.
Translated: There's always a Wii or a computer connected to the Internet, and every community has an Internet or somewhere.

Sentence 36:
Thai:       Lodin ยังกล่าวอีกว่าเจ้าหน้าที่ตัดสินใจยกเลิกการเลือกตั้งซ้ำเพื่อเป็นการประหยัดค่าใช้จ่ายและป้องกันความเสี่ยงด้านความปลอดภัยของการเลือกตั้งอื่นให้กับชาวอัฟกานิสถาน
English:    Lodin also said officials decided to cancel the runoff in order to save Afghans the expense and security risk of another election.
Translated: Lotin also said that the authorities decided to cancel the election to save the cost and prevent the safety of other elections for the Afghanistanns.

Sentence 37:
Thai:       ในบางประเทศที่มีรัฐบาลกลาง เช่น สหรัฐอเมริกา และแคนาดา จะมีการเรียกเก็บภาษีเงินได้ทั้งในระดับรัฐบาลกลางและในระดับท้องถิ่น ด้วยเหตุนี้ อัตราและขั้นภาษีอาจแตกต่างกันไปในแต่ละภูมิภาค
English:    In some federal countries, such as the United States and Canada, income tax is levied both at the federal level and at the local level, so the rates and brackets can vary from region to region.
Translated: In some countries where the federal government, such as the United States and Canada, is required to collect taxes on both federal and local levels, thus maybe the rate and the tax level are different in each region.

Sentence 38:
Thai:       โดยทั่วไปคุณจะต้องประกาศการให้ความช่วยเหลือของคุณ เดินไปตามท่าเรือ เข้าหาผู้คนที่กำลังทำความสะอาดเรือยอตช์ พยายามติดต่อกับกะลาสีเรือในบาร์ และอื่น ๆ
English:    Basically you'll be putting up notices offering your help, pacing the docks, approaching people cleaning their yachts, trying to make contact with sailors in the bar, etc.
Translated: In general, you need to declare your aid, walking along the docks towards the people who are cleaning the yacht, trying to contact sailors in bars, and so forth.

Sentence 39:
Thai:       ผู้ประท้วงหวังจะรวบรวมรายชื่อผู้ร้องเรียนได้ถึง 1.2 ล้านรายชื่อเพื่อเสนอต่อสภาคองเกรสในเดือนพฤศจิกายน
English:    Protesters hope to collect a petition of 1.2 million signatures to present to the National Congress in November.
Translated: The protesters are hoping to gather 1.2 million complaints to the Congress in November.

Sentence 40:
Thai:       ธารน้ำแข็งไม่จับตัวแข็งมากนัก แต่มันไหลลงไปตามภูเขา ซึ่งเป็นสาเหตุของรอยแตกและรอยแยกของน้ำแข็งบนภูเขา ซึ่งอาจจะถูกสะพานหิมะปกคลุมไว้
English:    The glaciers are not stable, but flow down the mountain. This will cause cracks, crevasses, which may be obscured by snow bridges.
Translated: The glaciers aren't very solid, but they flow down the mountain, which causes cracks and ice cracks in the mountains, which may be covered by the snow bridge.

Sentence 41:
Thai:       Cinque Terre ซึ่งหมายความว่าห้าดินแดน ประกอบด้วยหมู่บ้านชายฝั่งห้าหมู่บ้าน ได้แก่ Riomaggiore, Manarola, Corniglia, Vernazza และ Monterosso ซึ่งตั้งอยู่ในแคว้น Liguria ประเทศอิตาลี
English:    Cinque Terre, which means Five Lands, comprises the five small coastal villages of Riomaggiore, Manarola, Corniglia, Vernazza and Monterosso located in the Italian region of Liguria.
Translated: Cinque Terre, which means five lands consisting of five coastal villages, including Ryomagure, Manalola, Cornelius, Verza and Monteroso, which are located in Lyguria, Italy.

Sentence 42:
Thai:       แม้จะยังไม่ถึงขั้นเป็นปรากฏการณ์แห่งโลกยุคใหม่ แต่คนส่วนใหญ่ก็อาจเชื่อมโยงสิ่งนี้กับเยาวชนที่ใช้สีสเปรย์ฉีดทำลายทรัพย์สินสาธารณะและทรัพย์สินส่วนบุคคล
English:    While it's far from a modern phenomenon, most people probably associate it with youth vandalizing public and private property using spray paint.

## **2.2 M2M-100**

In [42]:
from transformers import M2M100ForConditionalGeneration, M2M100Tokenizer

# Get the M2M100 model and tokenizer
model = M2M100ForConditionalGeneration.from_pretrained("facebook/m2m100_418M")
tokenizer = M2M100Tokenizer.from_pretrained("facebook/m2m100_418M")

# Set Thai as source language
tokenizer.src_lang = "th"

# Simple translation function
def translate_m2m(thai_text):
    tokens = tokenizer(thai_text, return_tensors="pt")
    generated = model.generate(**tokens, forced_bos_token_id=tokenizer.get_lang_id("en"))
    return tokenizer.batch_decode(generated, skip_special_tokens=True)[0]

# Translate each pair
for i, (thai, eng) in enumerate(random_pairs):
    m2m_translation = translate_m2m(thai)
    print(f"\nPair {i + 1}:")
    print(f"Thai:     {thai}")
    print(f"English:  {eng}")
    print(f"M2M:      {m2m_translation}")

model.safetensors:   0%|          | 0.00/1.94G [00:00<?, ?B/s]

Pair 1:
Thai:       นี่ไม่ใช่กลุ่มอาการขาดทักษะด้านการเรียนรู้ แต่เป็นความผิดปกติทางการเรียนรู้ โรคนี้ "ส่งผลกระทบต่อเด็กร้อยละ 3 ถึง 5 ซึ่งอาจเป็นเด็กอเมริกันมากถึง 2 ล้านคน"
English:    It is not a learning disability, it is a learning disorder; it "affects 3 to 5 percent of all children, perhaps as many as 2 million American children".
M2M:        This is not a group of learning failure, but a learning disorder. This disease "affects 3 to 5 per child, which may be up to 2 million American children."

Pair 2:
Thai:       ผู้ที่ไม่คุ้นเคยกับศัพท์เฉพาะทางการแพทย์คิดว่า คำว่าติดเชื้อและโรคติดต่อนั้นมีความหมายต่างกัน
English:    For those unfamiliar with medical jargon, the words infectious and contagious have distinct meanings.
M2M:        People who are not familiar with the specific medical term think that the word infection and contact disease have different meanings.

Pair 3:
Thai:       เขาตั้งข้อสังเกตว่า งานวิจัยบางชิ้นชี้ให้เห็นว่าโรคนี้จำเป็นต้องมีอันตรายน้อยลงก่อนที่มันจะแพร่ระบาดไปทั่วโลก
English:    Some studies suggest that the disease must become less lethal before it can cause a global epidemic, he noted.
M2M:        He noted that some research suggests that the disease needs to be less dangerous before it spreads throughout the world.

Pair 4:
Thai:       นักวิทยาศาสตร์รายอื่น ๆ แย้งว่าพืชเหล่านี้มีพิษร้ายแรง จึงไม่น่าเป็นไปได้ที่จะมีไดโนเสาร์ตัวใดกินพวกมันได้ แม้ว่าในปัจจุบันสลอธและสัตว์อื่น ๆ เช่น นกแก้ว (ลูกหลานของไดโนเสาร์) จะสามารถกินใบไม้หรือผลไม้มีพิษได้ก็ตาม
English:    Other scientists argue that these plants are very poisonous so it is unlikely that any dinosaur ate them, even though today the sloth and other animals like the parrot (a descendant of the dinosaurs) can eat poisonous leaves or fruit.
M2M:        Other scientists say these plants are seriously poisonous. Therefore it is unlikely that any dinosaurs eat them. Although today slots and other animals, such as glass birds (the descendants of the dinosaurs), can eat toxic leaves or fruits.

Pair 5:
Thai:       ถึงแม้คุณอาจเคยได้ยินชาวกรีนแลนด์ใช้คำนี้ แต่ชาวต่างชาติไม่ควรใช้
English:    While you may hear the word used by Greenlandic Natives, its use should be avoided by foreigners.
M2M:        Although you may have heard Greek people use this word, foreigners should not use it.

Pair 6:
Thai:       นอกจากนี้ยังไม่มีข้อกำหนดว่าคุณจะต้องwfhรับหมายเลขท้องถิ่นจากชุมชนที่คุณอาศัยอยู่ คุณสามารถรับการเชื่อมต่ออินเทอร์เน็ตผ่านดาวเทียมในชิกเก้นซึ่งเป็นเมืองที่ห่างไกลความเจริญในอลาสก้า และเลือกหมายเลขที่บ่งบอกว่าคุณอยู่ในแอริโซนาที่มีแสงแดดจ้า
English:    There is also no requirement that you obtain a local number from the community in which you live; you can obtain a satellite Internet connection in the wilds of Chicken, Alaska and select a number which claims you're in sunny Arizona.
M2M:        There is also no requirement that you will have to wfh get a local number from the community you live. You can get a satellite Internet connection in Chicago, which is a remote city of prosperity in Alaska. And select a number that indicates that you are in Arizona with sunlight.

Pair 7:
Thai:       โฮสเทลแห่งหนึ่งถล่มในเมกกะซึ่งเป็นเมืองศักดิ์สิทธิ์ของศาสนาอิสลามเมื่อเวลาประมาณ 10 นาฬิกาของเช้าวันนี้ตามเวลาท้องถิ่น
English:    A hostel collapsed in Mecca, the holy city of Islam at about 10 o'clock this morning local time.
M2M:        One hostel in Mexico, which is the sacred city of Islam at about 10 a.m. this morning by local time.

Pair 8:
Thai:       ถึงอย่างนั้นก็คาดได้เลยว่าจะต้องหายใจหอบ และต้องระวังในส่วนที่ลาดชันกว่าโดยเฉพาะเมื่อเปียก เนื่องจากอาจเกิดอันตรายได้อย่างรวดเร็ว
English:    That said, expect to be out of breath, and take care in the steeper portions, especially when wet, as it can become dangerous quickly.
M2M:        In this case, it is expected to have to breathe and be careful in the more smooth areas, especially when wet. Because it can be damaged quickly.

Pair 9:
Thai:       ความเชื่อทางไสยศาสตร์สามารถจำแนกออกจากรูปแบบความเชื่อทางศาสนาและการบูชาอื่น ๆ ด้วยลักษณะที่เน้นในเรื่องประสบการณ์ตรงของการตระหนักรู้ในภาวะต่าง ๆ โดยเฉพาะภาวะของความรู้สึกสงบ การหยั่งรู้ ความผาสุก หรือแม้แต่ความปิติยินดีเหลือล้น
English:    Mysticism can be distinguished from other forms of religious belief and worship by its emphasis on the direct personal experience of a unique state of consciousness, particularly those of a peaceful, insightful, blissful, or even ecstatic character.
M2M:        Theological beliefs can be classified out of the forms of religious beliefs and other instinct with a character that focuses on the direct experience of consciousness in various conditions, in particular the state of sentimental calmness, discernment, discernment, or even untouched pleasure.

Pair 10:
Thai:       สัตว์ป่าอาจขี้อายหรือก้าวร้าวก็ได้ สภาพแวดล้อมอาจเย็น ร้อน หรือยากลำบาก
English:    Wild animals might either be shy or aggressive. The environment might be cold, hot, or otherwise hostile.
M2M:        Wild animals may be violent or aggressive. The environment may be cold, hot or difficult.

Pair 11:
Thai:       ปีเตอร์ เลนซ์ นักแข่งรถมอเตอร์ไซค์วัย 13 ปี เสียชีวิตหลังจากอยู่ในอุบัติเหตุรถชนกันที่อินเดียนาโปลิสมอเตอร์สปีดเวย์
English:    Peter Lenz, a 13-year-old motorcycle racer, has died after being involved in a crash at the Indianapolis Motor Speedway.
M2M:        Peter Lens, a 13-year-old motorcycle rider, has died after a crash in India's Polish Motorcycle Speedway.

Pair 12:
Thai:       ข่าวแพร่สะพัดในชุมชนเรดเลคในวันนี้ว่ามีนักเรียนอีกคนถูกจับุมจากการก่อเหตุกราดยิงในโรงเรียนเมื่อวันที่ 21 มีนาคม ขณะที่งานศพของ Jeff Weise และเหยื่อ 3 ใน 9 คนดำเนินอยู่
English:    News spread in the Red Lake community today as funerals for Jeff Weise and three of the nine victims were held that another student was arrested in connection with the school shootings of March 21.
M2M:        News spread in the Redleck community today that another student was arrested for a school massacre on March 21. While Jeff Weise's massacre and 3 in 9 victims are ongoing.

Pair 13:
Thai:       การปฏิบัติตามหลักการโภชนาการที่เหมาะสมแค่อย่างเดียวไม่สามารถช่วยให้เกิดสมรรถภาพระดับดีเลิศได้ แต่อาจส่งผลอย่างมากต่อสุขภาพโดยรวมของนักกีฬารุ่นเยาว์
English:    Proper nutritional practices alone cannot generate elite performances, but they can significantly affect young athletes' overall wellness.
M2M:        Compliance with the principles of proper nutrition in a single step can not contribute to an excellent performance level, but can greatly affect the overall health of young athletes.

Pair 14:
Thai:       พายุลูกนี้อยู่ห่างจากเมืองไมอามี่ในรัฐฟลอริดาราว 3,000 ไมล์โดยมีแรงลมสูงสุดอยู่ที่ 40 ไมล์/ชม. (64 กม./ชม.)
English:    The storm, located approximately 3,000 miles from Miami, Florida, has maximum sustained winds of 40 mph (64 kph).
M2M:        This bull is 3,000 miles away from Miami, Florida, with a maximum wind power of 40 miles/h. (64 km/h.)

Pair 15:
Thai:       ทฤษฎีนี้ย้อนแย้งกับคำกล่าวอ้างที่ว่า ดวงจันทร์นั้นไม่มีความเคลื่อนไหวทางธรณีวิทยาเลยแม้แต่น้อย
English:    This theory contradicts the claim that the moon is completely devoid of geologic activity.
M2M:        This theory is contrary to the claim that the moon has no geological movement at all, even a little.

Pair 16:
Thai:       การเข้าวัดจะต้องใช้บัตร Angkor Pass ดังนั้นเมื่อจะเดินทางไปโตนเลสาบ โปรดอย่าลืมนำหนังสือเดินทางติดตัวไปด้วย
English:    The Angkor Pass is needed to enter the temple so do not forget to bring your passport along when heading to Tonle Sap.
M2M:        Measurement requires an Angkor Pass card, so when you’re traveling to Tonnell, please don’t forget to bring your passport with you.

Pair 17:
Thai:       เมื่อประชากรทั้งหมดมีลักษณะทางพันธุกรรมอย่างหนึ่งที่เหมือนกันก็จะถูกเรียกว่าโมโนมอร์ฟิก
English:    When all individuals in a population are identical with regard to a particular phenotypic trait they are known as monomorphic.
M2M:        When all populations have the same genetic characteristics, it is called monomorphic.

Pair 18:
Thai:       ส่วนใหญ่แล้วจะเกิดขึ้นกับคนที่ทำงานเกี่ยวข้องกับสัตว์ปีกมากกว่า แต่นักดูนกก็มีความเสี่ยงเช่นกัน
English:    Most have involved people who work with poultry, but there is also some risk to birdwatchers.
M2M:        Mostly, it occurs with people who work more related to birds. But birds are also at risk.

Pair 19:
Thai:       แม้คุณอาจจะคิดว่าเป็นเรื่องดีที่จะใช้บริการสายการบินเดิม ๆ ที่คุณบินด้วยบ่อยที่สุด แต่ควรทราบไว้ว่าสิทธิพิเศษที่แต่ละสายการบินมอบให้มักจะแตกต่างกัน และคะแนนไมล์สะสมของสายการบินอื่นในกลุ่มพันธมิตรเดียวกันอาจให้ผลตอบแทนที่เป็นประโยชน์มากกว่า
English:    Although you may think it is intuitive to join the airline you fly most, you should be aware that privileges offered are often different and frequent flyer points may be more generous under a different airline in the same alliance.
M2M:        Even if you might think it’s good to use the original airline services you fly with the most frequently, it should be noted that the special benefits that each airline offers are often different. And the accumulated mile score of other airlines in the same group of partners may provide more profitable rewards.

Pair 20:
Thai:       หินบางชนิดที่หาได้ยากมากในโลก มีการขายตั้งแต่ราคา 11,000 ดอลลาร์สหรัฐไปจนถึง 22,500 ดอลลาร์สหรัฐต่อออนซ์ ซึ่งแพงกว่าราคาทองคำราวสิบเท่า
English:    Some of the rocks, which are very rare on Earth, are being sold from US$11,000 to $22,500 per ounce, which is about ten times more than the cost of gold.
M2M:        Some of the stones are very difficult to find in the world. They are sold from $11,000 to $22,500 per ounce, which is ten times more expensive than the gold price.

Pair 21:
Thai:       เนื่องจากด้านล่างของใบมีดโค้งเล็กน้อย เมื่อใบมีดเอียงไปด้านใดด้านหนึ่ง ขอบที่สัมผัสกับน้ำแข็งจึงโค้งเช่นกัน
English:    Because the bottom of the blade is slightly curved, as the blade tilts to one side or the other, the edge which is in contact with the ice also curves.
M2M:        Because the bottom of the knife is slightly curved. When the knife goes to any side, the ice-touched edge is also curved.

Pair 22:
Thai:       อย่างไรก็ตาม ในปัจจุบันศิลปินกราฟฟิตีที่ได้รับการยอมรับ มีงานอีเวนต์กราฟฟิตี และกำแพง สำหรับวาดภาพกราฟฟิตีที่ "ถูกกฎหมาย" ภาพวาดกราฟฟิตีในบริบทนี้มักคล้ายกับงานศิลปะมากกว่าป้ายที่อ่านไม่ออก
English:    However, nowadays there are established graffiti artists, graffiti events and "legal" walls. Graffiti paintings in this context often resemble artworks rather than illegible tags.
M2M:        However, at present, graphic artists are acknowledged with Events, graphic works and walls. For "legal" graphic drawings, graphic drawings in this context are often more similar to artwork than unread labels.

Pair 23:
Thai:       การที่วาล์วเปิดทำให้แรงดันถูกปล่อยออกจากระบบ แล้วน้ำมันก็ไหลไปตามรางสู่ถังที่มีความจุ 55,000 บาร์เรล (2.3 ล้านแกลลอน)
English:    The valves opening allowed a pressure release for the system and oil flowed on a pad to a tank that can hold 55,000 barrels (2.3 million gallons).
M2M:        The opening of the valve causes the pressure to be released from the system. Then the oil flows along the thread to a tank with a capacity of 55,000 barrel (2.3 million gallons).

Pair 24:
Thai:       ภาษาเสริมคือภาษาประดิษฐ์หรือภาษาที่สร้างขึ้นโดยมีวัตถุประสงค์เพื่ออำนวยความสะดวกในการสื่อสารระหว่างผู้คนที่อาจมีปัญหาในการสื่อสารหากไม่มีภาษานี้
English:    Auxiliary languages are artificial or constructed languages created with the intent of facilitating communication between peoples who would otherwise have difficulty communicating.
M2M:        Additional language is an artificial language or language created for the purpose of facilitating communication between people who may have trouble communicating without this language.

Pair 25:
Thai:       โบเบ็ก เกิดในซาเกร็บซึ่งเป็นเมืองหลวงของโครเอเชียและมีชื่อเสียงขึ้นมาขณะเล่นให้กับปาร์ติซานเบลเกรด
English:    Born in the Croatian capital, Zagreb, Bobek gained fame while playing for Partizan Belgrade.
M2M:        Bobby was born in Sakraba, which is the capital of Croatia and became famous as playing for Partisan Bell Grade.

Pair 26:
Thai:       นักวิทยาศาสตร์ได้ค้นพบรูปแบบของเปลือกโลกที่เรียกว่า lobate scarp กระจัดกระจายอยู่ทั่วพื้นผิวดวงจันทร์ ซึ่งปรากฏว่าเป็นผลมาจากการที่ดวงจันทร์หดตัวช้ามาก
English:    Scientists have discovered landforms littered across the moon's surface called lobate scarps that have apparently resulted from the moon's shrinking very slowly.
M2M:        Scientists have discovered a form of the globe, called the scarp lobate, which is spread throughout the moon's surface, which appears to be a result of the very slow moon shrinking.

Pair 27:
Thai:       ชูมัคเกอร์ซึ่งเกษียณในปี 2006 หลังจากที่คว้าแชมป์ฟอร์มูล่าวันไปเจ็ดครั้ง ต้องเข้ามาทำหน้าที่แทนเฟลิเป้ มาสซาซึ่งได้รับบาดเจ็บ
English:    Schumacher who retired in 2006 after winning the Formula 1 championship seven times, was due to replace the injured Felipe Massa.
M2M:        Chucker, who retired in 2006, after winning the championship for seven days. He must come to the post to replace Flippe Massa, who was injured.

Pair 28:
Thai:       HK Management Inc. ซึ่งเป็นบริษัทจัดการของวงไม่ได้ให้เหตุผลเบื้องต้นตอนที่พวกเขายกเลิกในวันที่ 20 กันยายน แต่วันรุ่งขึ้นก็กล่าวโทษเหตุผลที่มีตรรกะต่าง ๆ
English:    The band's management company, HK Management Inc., gave no initial reason when they canceled on September 20, but blamed logistical reasons by the next day.
M2M:        HK Management Inc., which is the group’s managing company, did not give any reason in advance when they withdrew on September 20, but tomorrow it will punish for various logical reasons.

Pair 29:
Thai:       มีค่าธรรมเนียมเพิ่มเติมสำหรับการเดินทางโดยมีผู้โดยสารมากกว่า 2 คน ตัวเลือกนี้จึงอาจมีราคาแพงกว่าที่จำเป็น
English:    There is a surcharge for having more than 2 passengers, so this option might be more expensive than necessary.
M2M:        There are additional fees for travel with more than 2 passengers. This option may be more expensive than necessary.

Pair 30:
Thai:       กลุ่มเต้นรำ Fire of Anatolia ของตุรกี ได้แสดงการเต้นรำชุด "Troy" เพื่อจบการแสดง
English:    To finish, Turkish dance group Fire of Anatolia performed the show "Troy".
M2M:        The Turkish Fire of Anatolia dance group showed the dance series "Troy" to finish the show.

Pair 31:
Thai:       บุคคลที่มีส่วนเกี่ยวข้องมาหลายสิบปีช่วยให้เราชื่นชมจุดแข็งและความหลงใหลของตัวเอง พร้อมทั้งประเมินความยากลำบากและกระทั่งความล้มเหลวอย่างตรงไปตรงมาในขณะเดียวกัน
English:    Individuals who had been involved for several decades helped us appreciate our strengths and passions while candidly assessing difficulties and even failures.
M2M:        The person involved for decades has helped us to appreciate our own strength and passion. At the same time, both assessing difficulties and even failures directly.

Pair 32:
Thai:       แอปแปลข้อความตามเวลาจริง - แอปพลิเคชั่นที่สามารถแปลข้อความทั้งส่วนจากภาษาหนึ่งเป็นอีกภาษาได้โดยอัตโนมัติ
English:    Real-time text translator apps – applications that are capable of automatically translating whole segments of text from one language into another.
M2M:        Real-time text translation app - an application that can automatically translate all parts of the text from one language to another.

Pair 33:
Thai:       ในกรณีนี้ การนึกถึงตัวอย่างพฤติกรรมแบบผู้บริหารและผลลัพธ์ความสำเร็จที่ตามมาช่วยให้ผู้คนเปิดรับความเปลี่ยนแปลงและแนวทางใหม่ๆ สำหรับคริสตจักรในท้องถิ่น
English:    In this instance, recalling previous instances of entrepreneurial behavior and resulting successes helped people to be open to new changes and new direction for the local church.
M2M:        In this case, considering the examples of managerial behavior and the followed success results helps people open up new changes and guidelines for the local church.

Pair 34:
Thai:       หลังจากเกิดเพลิงไหม้ ป้อมปราการได้รับการอนุรักษ์และปกป้อง และยังคงเป็นสถานที่ท่องเที่ยวที่น่าตื่นตาตื่นใจที่สุดแห่งหนึ่งของภูฏาน
English:    After the fire, the fortress was preserved and protected, remaining to be one of Bhutan's most sensational attractions.
M2M:        After a fire, the castle was preserved and protected. And remains one of the most amazing tourist attractions in the mountains.

Pair 35:
Thai:       โรงแรมหรือเจ้าบ้านของคุณ (กรณีที่คุณพักในเกสต์เฮาส์หรือบ้านส่วนตัว) มักจะมี wifi หรือคอมพิวเตอร์ที่ต่อกับอินเทอร์เน็ต และทุกชุมชนจะมีร้านอินเทอร์เน็ตหรือบางที่ก็มี wifi สาธารณะ
English:    Your hotel or hosts (if staying in a guesthouse or private home) will likely have wifi or an internet connected PC, and all settlements have an internet cafe or some location with public wifi.
M2M:        Your hotel or hostel (if you stay in a guest house or private house) usually has a wifi or a computer that connects to the internet. And every community has an internet store or some that has a public wifi.

Pair 36:
Thai:       Lodin ยังกล่าวอีกว่าเจ้าหน้าที่ตัดสินใจยกเลิกการเลือกตั้งซ้ำเพื่อเป็นการประหยัดค่าใช้จ่ายและป้องกันความเสี่ยงด้านความปลอดภัยของการเลือกตั้งอื่นให้กับชาวอัฟกานิสถาน
English:    Lodin also said officials decided to cancel the runoff in order to save Afghans the expense and security risk of another election.
M2M:        Lodin also said the officials decided to cancel the re-election to save costs and prevent the security risks of another election to the Afghan citizens.

Pair 37:
Thai:       ในบางประเทศที่มีรัฐบาลกลาง เช่น สหรัฐอเมริกา และแคนาดา จะมีการเรียกเก็บภาษีเงินได้ทั้งในระดับรัฐบาลกลางและในระดับท้องถิ่น ด้วยเหตุนี้ อัตราและขั้นภาษีอาจแตกต่างกันไปในแต่ละภูมิภาค
English:    In some federal countries, such as the United States and Canada, income tax is levied both at the federal level and at the local level, so the rates and brackets can vary from region to region.
M2M:        In some countries with central governments such as the United States and Canada, financial taxes will be charged both at the central and local level. Therefore, rates and taxes may vary in each region.

Pair 38:
Thai:       โดยทั่วไปคุณจะต้องประกาศการให้ความช่วยเหลือของคุณ เดินไปตามท่าเรือ เข้าหาผู้คนที่กำลังทำความสะอาดเรือยอตช์ พยายามติดต่อกับกะลาสีเรือในบาร์ และอื่น ๆ
English:    Basically you'll be putting up notices offering your help, pacing the docks, approaching people cleaning their yachts, trying to make contact with sailors in the bar, etc.
M2M:        In general, you have to announce your assistance. Go through the port. Find those who are cleaning the yacht. Try to contact the boats in the bar and so on.

Pair 39:
Thai:       ผู้ประท้วงหวังจะรวบรวมรายชื่อผู้ร้องเรียนได้ถึง 1.2 ล้านรายชื่อเพื่อเสนอต่อสภาคองเกรสในเดือนพฤศจิกายน
English:    Protesters hope to collect a petition of 1.2 million signatures to present to the National Congress in November.
M2M:        The opponents are hoping to collect up to 1.2 million lists of complaints to submit to the Senate in November.

Pair 40:
Thai:       ธารน้ำแข็งไม่จับตัวแข็งมากนัก แต่มันไหลลงไปตามภูเขา ซึ่งเป็นสาเหตุของรอยแตกและรอยแยกของน้ำแข็งบนภูเขา ซึ่งอาจจะถูกสะพานหิมะปกคลุมไว้
English:    The glaciers are not stable, but flow down the mountain. This will cause cracks, crevasses, which may be obscured by snow bridges.
M2M:        The ice sheet doesn’t catch so hard, but it flows down to the mountains, which is the cause of fractures and separation of the ice on the mountains. It may be covered by snow bridges.

Pair 41:
Thai:       Cinque Terre ซึ่งหมายความว่าห้าดินแดน ประกอบด้วยหมู่บ้านชายฝั่งห้าหมู่บ้าน ได้แก่ Riomaggiore, Manarola, Corniglia, Vernazza และ Monterosso ซึ่งตั้งอยู่ในแคว้น Liguria ประเทศอิตาลี
English:    Cinque Terre, which means Five Lands, comprises the five small coastal villages of Riomaggiore, Manarola, Corniglia, Vernazza and Monterosso located in the Italian region of Liguria.
M2M:        Cinque Terre, which means five territories, consists of five coastal villages, including Riomaggiore, Manarola, Corniglia, Vernazza and Monterosso, which are located in the Liguria square, Italy.

Pair 42:

## **2.3 MBART-50**

In [43]:
from transformers import MBartForConditionalGeneration, MBart50TokenizerFast

# Get the mBART model and tokenizer
model = MBartForConditionalGeneration.from_pretrained("facebook/mbart-large-50-many-to-many-mmt")
tokenizer = MBart50TokenizerFast.from_pretrained("facebook/mbart-large-50-many-to-many-mmt")

# Set Thai as source language
tokenizer.src_lang = "th_TH"

# Simple translation function
def translate_mbart(thai_text):
    tokens = tokenizer(thai_text, return_tensors="pt")
    generated = model.generate(**tokens, forced_bos_token_id=tokenizer.lang_code_to_id["en_XX"])
    return tokenizer.batch_decode(generated, skip_special_tokens=True)[0]

# Translate each pair
for i, (thai, eng) in enumerate(random_pairs):
    mbart_translation = translate_mbart(thai)
    print(f"\nPair {i + 1}:")
    print(f"Thai:     {thai}")
    print(f"English:  {eng}")
    print(f"mBART:    {mbart_translation}")

Pair 1:
Thai:       นี่ไม่ใช่กลุ่มอาการขาดทักษะด้านการเรียนรู้ แต่เป็นความผิดปกติทางการเรียนรู้ โรคนี้ "ส่งผลกระทบต่อเด็กร้อยละ 3 ถึง 5 ซึ่งอาจเป็นเด็กอเมริกันมากถึง 2 ล้านคน"
English:    It is not a learning disability, it is a learning disorder; it "affects 3 to 5 percent of all children, perhaps as many as 2 million American children".
mBART:      We're talking about skills shortages, diseases, diseases that affect three to five percent of Americans, maybe two to two percent of Americans.

Pair 2:
Thai:       ผู้ที่ไม่คุ้นเคยกับศัพท์เฉพาะทางการแพทย์คิดว่า คำว่าติดเชื้อและโรคติดต่อนั้นมีความหมายต่างกัน
English:    For those unfamiliar with medical jargon, the words infectious and contagious have distinct meanings.
mBART:      It used to be synonymous with specialized medicines, and diseases were synonymous.

Pair 3:
Thai:       เขาตั้งข้อสังเกตว่า งานวิจัยบางชิ้นชี้ให้เห็นว่าโรคนี้จำเป็นต้องมีอันตรายน้อยลงก่อนที่มันจะแพร่ระบาดไปทั่วโลก
English:    Some studies suggest that the disease must become less lethal before it can cause a global epidemic, he noted.
mBART:      He looked at some of the research to see if there was a disease, if there was a danger, if there was an epidemic.

Pair 4:
Thai:       นักวิทยาศาสตร์รายอื่น ๆ แย้งว่าพืชเหล่านี้มีพิษร้ายแรง จึงไม่น่าเป็นไปได้ที่จะมีไดโนเสาร์ตัวใดกินพวกมันได้ แม้ว่าในปัจจุบันสลอธและสัตว์อื่น ๆ เช่น นกแก้ว (ลูกหลานของไดโนเสาร์) จะสามารถกินใบไม้หรือผลไม้มีพิษได้ก็ตาม
English:    Other scientists argue that these plants are very poisonous so it is unlikely that any dinosaur ate them, even though today the sloth and other animals like the parrot (a descendant of the dinosaurs) can eat poisonous leaves or fruit.
mBART:      The phytoplankton was a highly toxic plant, so any dinosaur that had them could eat them, and now the salmon and the birds could eat the leaves or the toxic plants.

Pair 5:
Thai:       ถึงแม้คุณอาจเคยได้ยินชาวกรีนแลนด์ใช้คำนี้ แต่ชาวต่างชาติไม่ควรใช้
English:    While you may hear the word used by Greenlandic Natives, its use should be avoided by foreigners.
mBART:      You may have heard of the Greek word for word, the Greek word for word.

Pair 6:
Thai:       นอกจากนี้ยังไม่มีข้อกำหนดว่าคุณจะต้องwfhรับหมายเลขท้องถิ่นจากชุมชนที่คุณอาศัยอยู่ คุณสามารถรับการเชื่อมต่ออินเทอร์เน็ตผ่านดาวเทียมในชิกเก้นซึ่งเป็นเมืองที่ห่างไกลความเจริญในอลาสก้า และเลือกหมายเลขที่บ่งบอกว่าคุณอยู่ในแอริโซนาที่มีแสงแดดจ้า
English:    There is also no requirement that you obtain a local number from the community in which you live; you can obtain a satellite Internet connection in the wilds of Chicken, Alaska and select a number which claims you're in sunny Arizona.
mBART:      You can get a city number from the community, you can get a satellite number from Chicago, you can get a city number from Las Vegas, and you can get a city number from Arizona for sunlight.

Pair 7:
Thai:       โฮสเทลแห่งหนึ่งถล่มในเมกกะซึ่งเป็นเมืองศักดิ์สิทธิ์ของศาสนาอิสลามเมื่อเวลาประมาณ 10 นาฬิกาของเช้าวันนี้ตามเวลาท้องถิ่น
English:    A hostel collapsed in Mecca, the holy city of Islam at about 10 o'clock this morning local time.
mBART:      Hostels in the Islamic city of Meghalaya, about 10 clock in the clock in the Islamic city.

Pair 8:
Thai:       ถึงอย่างนั้นก็คาดได้เลยว่าจะต้องหายใจหอบ และต้องระวังในส่วนที่ลาดชันกว่าโดยเฉพาะเมื่อเปียก เนื่องจากอาจเกิดอันตรายได้อย่างรวดเร็ว
English:    That said, expect to be out of breath, and take care in the steeper portions, especially when wet, as it can become dangerous quickly.
mBART:      It's important to be aware of the risks associated with breathing inhalation and, in particular, of the risks associated with lung cancer.

Pair 9:
Thai:       ความเชื่อทางไสยศาสตร์สามารถจำแนกออกจากรูปแบบความเชื่อทางศาสนาและการบูชาอื่น ๆ ด้วยลักษณะที่เน้นในเรื่องประสบการณ์ตรงของการตระหนักรู้ในภาวะต่าง ๆ โดยเฉพาะภาวะของความรู้สึกสงบ การหยั่งรู้ ความผาสุก หรือแม้แต่ความปิติยินดีเหลือล้น
English:    Mysticism can be distinguished from other forms of religious belief and worship by its emphasis on the direct personal experience of a unique state of consciousness, particularly those of a peaceful, insightful, blissful, or even ecstatic character.
mBART:      Religious teachings can distinguish between religious teachings and worships, the specific nature of religious teachings from the consciousness of a state of affairs, in particular, the state of peace, of mind, of appetite, or of pleasure.

Pair 10:
Thai:       สัตว์ป่าอาจขี้อายหรือก้าวร้าวก็ได้ สภาพแวดล้อมอาจเย็น ร้อน หรือยากลำบาก
English:    Wild animals might either be shy or aggressive. The environment might be cold, hot, or otherwise hostile.
mBART:      It can be embarrassing or it can be awkward or it can be awkward or it can be difficult.

Pair 11:
Thai:       ปีเตอร์ เลนซ์ นักแข่งรถมอเตอร์ไซค์วัย 13 ปี เสียชีวิตหลังจากอยู่ในอุบัติเหตุรถชนกันที่อินเดียนาโปลิสมอเตอร์สปีดเวย์
English:    Peter Lenz, a 13-year-old motorcycle racer, has died after being involved in a crash at the Indianapolis Motor Speedway.
mBART:      A 13-year-old driver died in a car accident in Indianapolis, Indiana.

Pair 12:
Thai:       ข่าวแพร่สะพัดในชุมชนเรดเลคในวันนี้ว่ามีนักเรียนอีกคนถูกจับุมจากการก่อเหตุกราดยิงในโรงเรียนเมื่อวันที่ 21 มีนาคม ขณะที่งานศพของ Jeff Weise และเหยื่อ 3 ใน 9 คนดำเนินอยู่
English:    News spread in the Red Lake community today as funerals for Jeff Weise and three of the nine victims were held that another student was arrested in connection with the school shootings of March 21.
mBART:      The protests raged in Red Lake County, where another student was caught in a school shooting on March 21, the funeral of Jeff Weise, and three out of nine people were executed.

Pair 13:
Thai:       การปฏิบัติตามหลักการโภชนาการที่เหมาะสมแค่อย่างเดียวไม่สามารถช่วยให้เกิดสมรรถภาพระดับดีเลิศได้ แต่อาจส่งผลอย่างมากต่อสุขภาพโดยรวมของนักกีฬารุ่นเยาว์
English:    Proper nutritional practices alone cannot generate elite performances, but they can significantly affect young athletes' overall wellness.
mBART:      Applying the principles of nutrition for excellence in performance could contribute to the overall health of young athletes.

Pair 14:
Thai:       พายุลูกนี้อยู่ห่างจากเมืองไมอามี่ในรัฐฟลอริดาราว 3,000 ไมล์โดยมีแรงลมสูงสุดอยู่ที่ 40 ไมล์/ชม. (64 กม./ชม.)
English:    The storm, located approximately 3,000 miles from Miami, Florida, has maximum sustained winds of 40 mph (64 kph).
mBART:      A hurricane hit the city of Miami, Florida, 3,000 times its peak winds of 40 kilometers an hour.

Pair 15:
Thai:       ทฤษฎีนี้ย้อนแย้งกับคำกล่าวอ้างที่ว่า ดวงจันทร์นั้นไม่มีความเคลื่อนไหวทางธรณีวิทยาเลยแม้แต่น้อย
English:    This theory contradicts the claim that the moon is completely devoid of geologic activity.
mBART:      The theory of geology and the words of geology, of geology, of geology.

Pair 16:
Thai:       การเข้าวัดจะต้องใช้บัตร Angkor Pass ดังนั้นเมื่อจะเดินทางไปโตนเลสาบ โปรดอย่าลืมนำหนังสือเดินทางติดตัวไปด้วย
English:    The Angkor Pass is needed to enter the temple so do not forget to bring your passport along when heading to Tonle Sap.
mBART:      If you want to take an Angkor Pass, or if you want to go to a picnic, please bring your passport with you.

Pair 17:
Thai:       เมื่อประชากรทั้งหมดมีลักษณะทางพันธุกรรมอย่างหนึ่งที่เหมือนกันก็จะถูกเรียกว่าโมโนมอร์ฟิก
English:    When all individuals in a population are identical with regard to a particular phenotypic trait they are known as monomorphic.
mBART:      The populations are genetically identical and are affected by the physics of their genomes.

Pair 18:
Thai:       ส่วนใหญ่แล้วจะเกิดขึ้นกับคนที่ทำงานเกี่ยวข้องกับสัตว์ปีกมากกว่า แต่นักดูนกก็มีความเสี่ยงเช่นกัน
English:    Most have involved people who work with poultry, but there is also some risk to birdwatchers.
mBART:      We're going to work with the industry, we're going to work with the wing industry, we're going to work with the bird watching industry, we're going to work with the industry.

Pair 19:
Thai:       แม้คุณอาจจะคิดว่าเป็นเรื่องดีที่จะใช้บริการสายการบินเดิม ๆ ที่คุณบินด้วยบ่อยที่สุด แต่ควรทราบไว้ว่าสิทธิพิเศษที่แต่ละสายการบินมอบให้มักจะแตกต่างกัน และคะแนนไมล์สะสมของสายการบินอื่นในกลุ่มพันธมิตรเดียวกันอาจให้ผลตอบแทนที่เป็นประโยชน์มากกว่า
English:    Although you may think it is intuitive to join the airline you fly most, you should be aware that privileges offered are often different and frequent flyer points may be more generous under a different airline in the same alliance.
mBART:      Maybe you want to know about the best practices of the old airlines, the airlines that have the special rights to provide services, and the accumulated scores of the airlines in the same alliance can be a reward for those practices.

Pair 20:
Thai:       หินบางชนิดที่หาได้ยากมากในโลก มีการขายตั้งแต่ราคา 11,000 ดอลลาร์สหรัฐไปจนถึง 22,500 ดอลลาร์สหรัฐต่อออนซ์ ซึ่งแพงกว่าราคาทองคำราวสิบเท่า
English:    Some of the rocks, which are very rare on Earth, are being sold from US$11,000 to $22,500 per ounce, which is about ten times more than the cost of gold.
mBART:      Some of the world's most precious rocks have sold for as much as 11,000 U.S. dollars, up to 22,500 U.S. dollars, expensive gold for 10 cents.

Pair 21:
Thai:       เนื่องจากด้านล่างของใบมีดโค้งเล็กน้อย เมื่อใบมีดเอียงไปด้านใดด้านหนึ่ง ขอบที่สัมผัสกับน้ำแข็งจึงโค้งเช่นกัน
English:    Because the bottom of the blade is slightly curved, as the blade tilts to one side or the other, the edge which is in contact with the ice also curves.
mBART:      The boundary of the leaf, the boundary of which is adjacent to the leaf, the boundary of the contact with the leaf, therefore the boundary.

Pair 22:
Thai:       อย่างไรก็ตาม ในปัจจุบันศิลปินกราฟฟิตีที่ได้รับการยอมรับ มีงานอีเวนต์กราฟฟิตี และกำแพง สำหรับวาดภาพกราฟฟิตีที่ "ถูกกฎหมาย" ภาพวาดกราฟฟิตีในบริบทนี้มักคล้ายกับงานศิลปะมากกว่าป้ายที่อ่านไม่ออก
English:    However, nowadays there are established graffiti artists, graffiti events and "legal" walls. Graffiti paintings in this context often resemble artworks rather than illegible tags.
mBART:      Nowadays, accepted graphic artists have works of graphic arts, and walls for legal graphic arts, graphic arts in the context of art are often excluded.

Pair 23:
Thai:       การที่วาล์วเปิดทำให้แรงดันถูกปล่อยออกจากระบบ แล้วน้ำมันก็ไหลไปตามรางสู่ถังที่มีความจุ 55,000 บาร์เรล (2.3 ล้านแกลลอน)
English:    The valves opening allowed a pressure release for the system and oil flowed on a pad to a tank that can hold 55,000 barrels (2.3 million gallons).
mBART:      The opening of the pressurized economy was driven out of the system by the flow of 55,000 gallons of gasoline into the bucket.

Pair 24:
Thai:       ภาษาเสริมคือภาษาประดิษฐ์หรือภาษาที่สร้างขึ้นโดยมีวัตถุประสงค์เพื่ออำนวยความสะดวกในการสื่อสารระหว่างผู้คนที่อาจมีปัญหาในการสื่อสารหากไม่มีภาษานี้
English:    Auxiliary languages are artificial or constructed languages created with the intent of facilitating communication between peoples who would otherwise have difficulty communicating.
mBART:      Auxiliary languages are languages, or languages with an auxiliary language that might be a problem if you're using a language.

Pair 25:
Thai:       โบเบ็ก เกิดในซาเกร็บซึ่งเป็นเมืองหลวงของโครเอเชียและมีชื่อเสียงขึ้นมาขณะเล่นให้กับปาร์ติซานเบลเกรด
English:    Born in the Croatian capital, Zagreb, Bobek gained fame while playing for Partizan Belgrade.
mBART:      Bobe was born in Zagreb, the capital city of Croatia, and he had a voice while he was in Bratislava.

Pair 26:
Thai:       นักวิทยาศาสตร์ได้ค้นพบรูปแบบของเปลือกโลกที่เรียกว่า lobate scarp กระจัดกระจายอยู่ทั่วพื้นผิวดวงจันทร์ ซึ่งปรากฏว่าเป็นผลมาจากการที่ดวงจันทร์หดตัวช้ามาก
English:    Scientists have discovered landforms littered across the moon's surface called lobate scarps that have apparently resulted from the moon's shrinking very slowly.
mBART:      The world's lobate scarp phenomenon has been disrupted by the spread of the sun's skin, resulting in a dramatic reduction in sunlight.

Pair 27:
Thai:       ชูมัคเกอร์ซึ่งเกษียณในปี 2006 หลังจากที่คว้าแชมป์ฟอร์มูล่าวันไปเจ็ดครั้ง ต้องเข้ามาทำหน้าที่แทนเฟลิเป้ มาสซาซึ่งได้รับบาดเจ็บ
English:    Schumacher who retired in 2006 after winning the Formula 1 championship seven times, was due to replace the injured Felipe Massa.
mBART:      She retired in 2006 from the World Health Organization on behalf of Falun Gong, Massachusetts.

Pair 28:
Thai:       HK Management Inc. ซึ่งเป็นบริษัทจัดการของวงไม่ได้ให้เหตุผลเบื้องต้นตอนที่พวกเขายกเลิกในวันที่ 20 กันยายน แต่วันรุ่งขึ้นก็กล่าวโทษเหตุผลที่มีตรรกะต่าง ๆ
English:    The band's management company, HK Management Inc., gave no initial reason when they canceled on September 20, but blamed logistical reasons by the next day.
mBART:      HK Management Inc., the parent company of the rationale movement, when they abolished the 20th of September as the day of rationale punishment.

Pair 29:
Thai:       มีค่าธรรมเนียมเพิ่มเติมสำหรับการเดินทางโดยมีผู้โดยสารมากกว่า 2 คน ตัวเลือกนี้จึงอาจมีราคาแพงกว่าที่จำเป็น
English:    There is a surcharge for having more than 2 passengers, so this option might be more expensive than necessary.
mBART:      There's an option for two-person travel, so the choice may be expensive.

Pair 30:
Thai:       กลุ่มเต้นรำ Fire of Anatolia ของตุรกี ได้แสดงการเต้นรำชุด "Troy" เพื่อจบการแสดง
English:    To finish, Turkish dance group Fire of Anatolia performed the show "Troy".
mBART:      Turkey's Fire of Anatolia performance of the "Troy" series ended.

Pair 31:
Thai:       บุคคลที่มีส่วนเกี่ยวข้องมาหลายสิบปีช่วยให้เราชื่นชมจุดแข็งและความหลงใหลของตัวเอง พร้อมทั้งประเมินความยากลำบากและกระทั่งความล้มเหลวอย่างตรงไปตรงมาในขณะเดียวกัน
English:    Individuals who had been involved for several decades helped us appreciate our strengths and passions while candidly assessing difficulties and even failures.
mBART:      For decades, people have been looking at our goals and our passions and assessing our difficulties and our failures in a very honest way.

Pair 32:
Thai:       แอปแปลข้อความตามเวลาจริง - แอปพลิเคชั่นที่สามารถแปลข้อความทั้งส่วนจากภาษาหนึ่งเป็นอีกภาษาได้โดยอัตโนมัติ
English:    Real-time text translator apps – applications that are capable of automatically translating whole segments of text from one language into another.
mBART:      Apple translates texts in real time — Apple automatically translates texts from one language into another.

Pair 33:
Thai:       ในกรณีนี้ การนึกถึงตัวอย่างพฤติกรรมแบบผู้บริหารและผลลัพธ์ความสำเร็จที่ตามมาช่วยให้ผู้คนเปิดรับความเปลี่ยนแปลงและแนวทางใหม่ๆ สำหรับคริสตจักรในท้องถิ่น
English:    In this instance, recalling previous instances of entrepreneurial behavior and resulting successes helped people to be open to new changes and new direction for the local church.
mBART:      In the case of the Church, the implications of the behavioral conventions and the religious conventions followed the opening up of the religious conventions and the religious guidelines for the church in the conventions.

Pair 34:
Thai:       หลังจากเกิดเพลิงไหม้ ป้อมปราการได้รับการอนุรักษ์และปกป้อง และยังคงเป็นสถานที่ท่องเที่ยวที่น่าตื่นตาตื่นใจที่สุดแห่งหนึ่งของภูฏาน
English:    After the fire, the fortress was preserved and protected, remaining to be one of Bhutan's most sensational attractions.
mBART:      After the fire, the government and industry protested, and continued to protest against the government of Bhutan.

Pair 35:
Thai:       โรงแรมหรือเจ้าบ้านของคุณ (กรณีที่คุณพักในเกสต์เฮาส์หรือบ้านส่วนตัว) มักจะมี wifi หรือคอมพิวเตอร์ที่ต่อกับอินเทอร์เน็ต และทุกชุมชนจะมีร้านอินเทอร์เน็ตหรือบางที่ก็มี wifi สาธารณะ
English:    Your hotel or hosts (if staying in a guesthouse or private home) will likely have wifi or an internet connected PC, and all settlements have an internet cafe or some location with public wifi.
mBART:      Your hotel, or your community, usually has a WiFi, or community with WiFi, and every community has a community with some public WiFi.

Pair 36:
Thai:       Lodin ยังกล่าวอีกว่าเจ้าหน้าที่ตัดสินใจยกเลิกการเลือกตั้งซ้ำเพื่อเป็นการประหยัดค่าใช้จ่ายและป้องกันความเสี่ยงด้านความปลอดภัยของการเลือกตั้งอื่นให้กับชาวอัฟกานิสถาน
English:    Lodin also said officials decided to cancel the runoff in order to save Afghans the expense and security risk of another election.
mBART:      Lodin also decided to abolish the economic and safety sanctions on the Afghan people.

Pair 37:
Thai:       ในบางประเทศที่มีรัฐบาลกลาง เช่น สหรัฐอเมริกา และแคนาดา จะมีการเรียกเก็บภาษีเงินได้ทั้งในระดับรัฐบาลกลางและในระดับท้องถิ่น ด้วยเหตุนี้ อัตราและขั้นภาษีอาจแตกต่างกันไปในแต่ละภูมิภาค
English:    In some federal countries, such as the United States and Canada, income tax is levied both at the federal level and at the local level, so the rates and brackets can vary from region to region.
mBART:      In some countries, the federal governments of the United States and Canada will have to charge taxes on the federal level and on the causes, and rates and taxes may go to the regional governments.

Pair 38:
Thai:       โดยทั่วไปคุณจะต้องประกาศการให้ความช่วยเหลือของคุณ เดินไปตามท่าเรือ เข้าหาผู้คนที่กำลังทำความสะอาดเรือยอตช์ พยายามติดต่อกับกะลาสีเรือในบาร์ และอื่น ๆ
English:    Basically you'll be putting up notices offering your help, pacing the docks, approaching people cleaning their yachts, trying to make contact with sailors in the bar, etc.
mBART:      You're going to announce your destination, you're going to go to the shipyard, you're going to look for a cleaner, you're going to try to get the paint on the ship, and so on.

Pair 39:
Thai:       ผู้ประท้วงหวังจะรวบรวมรายชื่อผู้ร้องเรียนได้ถึง 1.2 ล้านรายชื่อเพื่อเสนอต่อสภาคองเกรสในเดือนพฤศจิกายน
English:    Protesters hope to collect a petition of 1.2 million signatures to present to the National Congress in November.
mBART:      The protest hopes to collect 1.2 million views on Congressional proposals in May.

Pair 40:
Thai:       ธารน้ำแข็งไม่จับตัวแข็งมากนัก แต่มันไหลลงไปตามภูเขา ซึ่งเป็นสาเหตุของรอยแตกและรอยแยกของน้ำแข็งบนภูเขา ซึ่งอาจจะถูกสะพานหิมะปกคลุมไว้
English:    The glaciers are not stable, but flow down the mountain. This will cause cracks, crevasses, which may be obscured by snow bridges.
mBART:      The rainfall is so heavy that it flows down the mountains, causing cracks and fractures in the mountains, possibly covered by snow bridges.

Pair 41:
Thai:       Cinque Terre ซึ่งหมายความว่าห้าดินแดน ประกอบด้วยหมู่บ้านชายฝั่งห้าหมู่บ้าน ได้แก่ Riomaggiore, Manarola, Corniglia, Vernazza และ Monterosso ซึ่งตั้งอยู่ในแคว้น Liguria ประเทศอิตาลี
English:    Cinque Terre, which means Five Lands, comprises the five small coastal villages of Riomaggiore, Manarola, Corniglia, Vernazza and Monterosso located in the Italian region of Liguria.
mBART:      Cinque Terre means land, men's land, Riomaggiore, Manarola, Corniglia, Vernazza and Monterosso, in the province of Liguria, Italy.

Pair 42:
Thai:       แม้จะยังไม่ถึงขั้นเป็นปรากฏการณ์แห่งโลกยุคใหม่ แต่คนส่วนใหญ่ก็อาจเชื่อมโยงสิ่งนี้กับเยาวชนที่ใช้สีสเปรย์ฉีดทำลายทรัพย์สินสาธารณะและทรัพย์สินส่วนบุคคล
English:    While it's far from a modern phenomenon, most people probably associate it with youth vandalizing public and private property using spray paint.
mBART:      It's a global phenomenon in the age of people, and it can affect young people, it can affect the destruction of public institutions and it can affect individuals.

Pair 43:
Thai:       เรามีวิกฤตการณ์ทางการเงินตลอดทั้งปี ซึ่งเป็นช่วงเวลาที่เลวร้ายที่สุดในช่วงสองเดือนที่ผ่านมา และผมคิดว่าตอนนี้ตลาดการเงินกำลังเริ่มฟื้นตัวแล้ว "
English:    We have a year-long financial crisis, which has had its most acute moment in the past two months, and I think now the financial markets are beginning to recover."
mBART:      We've got a financial crisis going on all year for two months, and I'm on the financial markets for the next two months."

Pair 44:
Thai:       การเดินป่าในช่วงกลางวันมีตั้งแต่ระยะทางน้อยกว่าหนึ่งไมล์ไปจนถึงระยะทางไกลกว่าซึ่งสามารถเดินได้จบได้ในวันเดียว

## **2.4 Data statistics**

In [45]:
import pandas as pd

# Simple function to get text length statistics
def get_text_stats(text_list):
    lengths = [len(text) for text in text_list]
    return {
        'min': min(lengths),
        'max': max(lengths),
        'avg': sum(lengths) // len(lengths)
    }

# Create table for source and target text
source_target_table = pd.DataFrame({
    'Sentences': ['Thai', 'English'],
    'Min length': [get_text_stats(thai_text)['min'], get_text_stats(english_text)['min']],
    'Avg length': [get_text_stats(thai_text)['avg'], get_text_stats(english_text)['avg']],
    'Max length': [get_text_stats(thai_text)['max'], get_text_stats(english_text)['max']]
})

# Create table for model translations
models_table = pd.DataFrame({
    'Model': ['OPUS-MT', 'M2M-100', 'MBART-50'],
    'Min length': [get_text_stats(opus_translations)['min'],
                  get_text_stats(m2m_translations)['min'],
                  get_text_stats(mbart_translations)['min']],
    'Avg length': [get_text_stats(opus_translations)['avg'],
                  get_text_stats(m2m_translations)['avg'],
                  get_text_stats(mbart_translations)['avg']],
    'Max length': [get_text_stats(opus_translations)['max'],
                  get_text_stats(m2m_translations)['max'],
                  get_text_stats(mbart_translations)['max']]
})

In [46]:
source_target_table

  Sentences  Min length  Avg length  Max length
0    Source          33         126         287
1    Target          28         132         273

In [47]:
models_table

      Model  Min length  Avg length  Max length
0   OPUS-MT          28         128         267
1   M2M-100          28         143         311
2  MBART-50          27         115         239

# **3. Results analysis and evaluation**

## **3.1 Results of each model**

In [48]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.translate import bleu_score

# Get NLTK data
nltk.download('punkt_tab')

# Process reference (original English) translations
english_tokens = [[word_tokenize(sent)] for sent in english_text]

# Process and score each model's translations
translation_sets = {
    'OPUS-MT': opus_translations,
    'M2M-100': m2m_translations,
    'MBART-50': mbart_translations
}

# Calculate and show BLEU scores
for model_name, translated_text in translation_sets.items():
    # Tokenize translated sentences
    model_tokens = [word_tokenize(sent) for sent in translated_text]

    # Get BLEU score
    bleu = bleu_score.corpus_bleu(english_tokens, model_tokens)

    # Print result
    print(f"\nBLEU score for {model_name}: {bleu:.4f}")

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

BLEU score for OPUS-MT: 0.2516

BLEU score for M2M-100: 0.2442

BLEU score for MBART-50: 0.1319

## **3.2 Results discussion**

The OPUS-MT model performed best with a BLEU score of 0.2516, showing its strength in Thai-English translation. M2M-100 came very close with a score of 0.2442, which is impressive for a multilingual model. MBART-50 scored much lower at 0.1319, possibly because its broader language coverage affected its Thai-English translation quality.