# **CS 584-A: Natural Language Processing**
# **Homework 1**

**Name: Ankit Dhandharia**

**CWID: 20033031**

## **Goals**
The goal of HW1 is for you to get familiar with extracting features and standard machine learning
workflows, including reading data, preprocessing data, training, testing, and evaluation. All those
are open questions and there is no fixed solution. The difference in data processing, parameter
initialization, data split, etc, will lead to the differences in final predications and evaluation results.
Therefore, during the grading, the specific values in the results are not important. It is important
that you focus on implementing the functions and setting up the pipelines.

## **Task: Sentiment Analysis with Text Classification**
Based on the dataset, the task is to perform sentiment analysis, which predicts the sentiments based
on the free-text reviews. We can simplify the task as a binary classification problem. Specifically, we will
consider the rating 4 and 5 as positive, rating 1 and 2 as negative and for data samples with neutral rating 3, we will discard them.

# **Mounting Drive**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# **Importing Python Libraries**

In [ ]:
import numpy as np
import pandas as pd
import nltk
import string
from nltk.corpus import stopwords
import re

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

# **Importing Dataset**

The dataset is about the product review dataset from Amazon. The dataset provides product reviews and overall ratings for 4,915 products. We will consider the fine-grained overall ratings as labels, which are ranging from 1 to 5: highly negative, negative, neutral, positive, and highly positive

In [ ]:
dataset = pd.read_csv('drive/MyDrive/amazon_reviews.csv')
dataset

      overall                                         reviewText
0           4                                         No issues.
1           5  Purchased this for my device, it worked as adv...
2           4  it works as expected. I should have sprung for...
3           5  This think has worked out great.Had a diff. br...
4           5  Bought it with Retail Packaging, arrived legit...
...       ...                                                ...
4910        1  I bought this Sandisk 16GB Class 10 to use wit...
4911        5  Used this for extending the capabilities of my...
4912        5  Great card that is very fast and reliable. It ...
4913        5  Good amount of space for the stuff I want to d...
4914        5  I've heard bad things about this 64gb Micro SD...

[4915 rows x 2 columns]

# **Tasks 1: Extracting features**

## **1. Data preparation**

### **1.1 Data preprocessing**
(i) converting all text to lowercase to ensure uniformity,

(ii) removing punctuations, numbers, and stopwords, and

(iii) tokenizing the reviews into tokens.

If you plan to work on the binary classification problem, you will need to assign binary class labels based on the above-mentioned strategy

In [ ]:
# Tokenization and stopwords setup
stop_words = set(stopwords.words('english'))

# Initialize an empty list to store cleaned texts
cleaned_texts = []

# Loop through the dataset to clean and tokenize each text
for text in dataset["reviewText"]:
    # Convert text to lowercase and remove punctuations/numbers
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = re.sub(r'\d', '', text)

    # Tokenize the cleaned text
    words = nltk.word_tokenize(text)

    # Filter out stopwords
    tokenized_text = [word for word in words if word not in stop_words]

    # Append cleaned and tokenized text to the list
    cleaned_texts.append(tokenized_text)

# Assign the cleaned texts back to the dataframe
dataset["reviewText"] = cleaned_texts

dataset

      overall                                         reviewText
0           4                                           [issues]
1           5  [purchased, device, worked, advertised, never,...
2           4  [works, expected, sprung, higher, capacity, th...
3           5  [think, worked, greathad, diff, bran, gb, card...
4           5  [bought, retail, packaging, arrived, legit, or...
...       ...                                                ...
4910        1  [bought, sandisk, gb, class, use, htc, inspire...
4911        5  [used, extending, capabilities, samsung, galax...
4912        5  [great, card, fast, reliable, comes, optional,...
4913        5  [good, amount, space, stuff, want, fits, gopro...
4914        5  [ive, heard, bad, things, gb, micro, sd, card,...

[4915 rows x 2 columns]

### **1.2 Data split**
Split the data with the ratio of 0.8, 0.1, and 0.1 into training, validation/development, and testing, respectively

In [ ]:
from sklearn.model_selection import train_test_split

train, temp = train_test_split(dataset, test_size=0.2, random_state=100) #Spliting dataset into training (80%) and remaining (20%)

val, test = train_test_split(temp, test_size=0.5, random_state=100) #Spliting the remaining 20% into validation (10%) and test (10%)

#Checking the shape of the splits to verify the ratios
print(f'Training set: {train.shape}')
print(f'Validation set: {val.shape}')
print(f'Test set: {test.shape}')

Training set: (3932, 2)
Validation set: (491, 2)
Test set: (492, 2)